### ISSUE TITLE
LovyanGFX_Clock on M5Stack Core2

### ISSUE THREAD

**Issue by ondrej1024** [lovyan03/LovyanGFX#100]
I flashed the LovyanGFX_Clock firmware on an M5Stack Core2 with M2Burner. Now the Core2 is not switching on again. Tried the reset and power buttons. 

Any idea what happened? Did I corrupt the boot flash? How can I recover the device?

Any idea welcome.

Thanks, Ondrej

**Comment by lovyan03** [comment]
Ah... that's not the farm I made. It's probably for M5Stack OLD Core.
If you write the firmware for Core2, it should come back.

**Comment by lovyan03** [comment]
The M5Stack staff imported the LovyanGFX sample code into M5Burner without consulting me, so they are not under my control.
I'm having a bit of trouble with that.

**Comment by ondrej1024** [comment]
> If you write the firmware for Core2, it should come back.

I had tried that but it didn't work. I was afraid I had bricked the device. Now I tried again and it worked :grinning: 

Yes, the firmware is probably only for the old Core device, but it doesn't mention it in the description of M5Burner.

Thanks for your help
