### ISSUE TITLE
Help documenting...

### ISSUE THREAD

**Issue by ropg** [lovyan03/LovyanGFX#104]
Hi there...

I'd like to help creating a truly english version of the documentation, and possibly create spiffy documentation on Read The Docs by creating a documentation source directory. Is there interest for that?

**Comment by ropg** [comment]
Have a look at PR #105. It's just a start of how it could be... I'd like feedback before doing lots of work...

**Comment by lovyan03** [comment]
Hello,  @ropg !
Thanks for your cooperation and very interesting offer.
In fact, I am very bad at English. I use the help of google and DeepL for translation.
Also, I understand that the documentation for LovyanGFX is quite lacking at the moment.

**Comment by ropg** [comment]
Better suited for discussions, not really an issue. See #111
