### ISSUE TITLE
drawJpgFile doesn't work with datum

### ISSUE THREAD

**Issue by kazyam53** [lovyan03/LovyanGFX#127]
I found that drawJpgFile can't display image if I set datum except top_left.
` lcd.drawJpgFile(SD, "/hoge.jpg", 0, 0,0, 0, 0, 0, 1.0, 1.0,top_left);  //Work`
`  lcd.drawJpgFile(SD, "/hoge.jpg", 0, 0,0, 0, 0, 0, 1.0, 1.0,top_center); //Can't display`

Unitil the commit 48bee0d, both works well but from the next(a6bfce4), it doesn't.
It also doesn't work on M5GFX.

Thank you in advance for your help.

**Comment by lovyan03** [comment]
@kazyam53 
This is not a problem, because the criteria cannot be determined without specifying the width and height to be displayed.
Try specifying the desired drawing size in width and height.

```
lcd.drawJpgFile(SD, "/hoge.jpg", 0, 0, lcd.width(), lcd.height(), 0, 0, 1.0, 1.0,top_center); 
```

**Comment by lovyan03** [comment]
The M5GFX jpg drawing sample contained a bug, which has been fixed.
Thank you very much .

**Comment by kazyam53** [comment]
It worked.
Thank you for your support.
