### ISSUE TITLE
Request LovyanGFX support for  ESP32-C3-DevKitM-1

### ISSUE THREAD

**Issue by BlynkGO** [lovyan03/LovyanGFX#134]
LovyanGFX is the great library for TFT.
And  now Arduino ESP32 core 2.0.0 alpha1 support with ESP32-C3-DevKitM-1.

I have tried to compile LovyanGFX  on  ESP32-C3-DevKitM-1. But it's not worked.
Do you mind to support LovyanGFX  for  ESP32-C3-DevKitM-1 too?
 
![image](https://user-images.githubusercontent.com/65327357/124383200-4c4ac980-dcf5-11eb-8ece-7151c297130a.png)

Thank you very much.

**Comment by lovyan03** [comment]
@BlynkGO 
Thank you for the request.
I don't have it yet, so I made arrangements.

**Comment by lovyan03** [comment]
@BlynkGO 
A new release has been created.
The SPI of ESP32-C3 is now available in the v1 specification.
It does not support DMA transfer yet, but you can try it anyway.

**Comment by BlynkGO** [comment]
Thank you very much.

**Comment by lovyan03** [comment]
@BlynkGO 
Sorry for the late notice.
Support for SPI bus and I2C bus of ESP32-C3 has been completed.

**Comment by javiser** [comment]
Great work @lovyan03! I have a ESP32C3 as well and got a basic example with esp-idf / platformio running but only after setting `cfg.dma_channel = 0;`. Just out of curiosity, are there any plans to implement DMA transfer? I will not open an issue for that myself.
