### ISSUE TITLE
Using Adafruit_GFX_Button

### ISSUE THREAD

**Issue by hanscomps** [lovyan03/LovyanGFX#137]
Hi,
I am new to the Touch LCD environment for ESP32 (but not arduino, ESP32 and C).
Is there a way to use the Adafruit_GFX_Button library or any other compatible touch button libraries for LovyanGFX?

Hans

**Comment by tobozo** [comment]
Hi,

[lvgl](https://github.com/lvgl/lvgl) works quite well with LovyanGFX.

**Comment by lovyan03** [comment]
@hanscomps 
I see. I didn't think there would be a demand for it.
I'll try to create the LGFX_Button class.

**Comment by hanscomps** [comment]
@lovyan03 Great thanks.
Will also take a look at lvgl, seems very polished and complete.
[so many libraries out there, bit bewildering]
