### ISSUE TITLE
Teensy 4.x

### ISSUE THREAD

**Issue by DIYLAB-DE** [lovyan03/LovyanGFX#149]
Hi,
is your library executable on Teensy 4.x?

Best
Bruno

**Comment by lovyan03** [comment]
@DIYLAB-DE 
Currently LovyanGFX does not support the Teensy series.
It is included in the support schedule, and I have one Teensy board available.

**Comment by DIYLAB-DE** [comment]
Thanks for the quick reply!
I hope you fall in love with the Teensy 4.x soon ;o)
