### ISSUE TITLE
using ssd1963

### ISSUE THREAD

**Issue by Ali-Abdelwdod** [lovyan03/LovyanGFX#158]
Does this library support ssd1963? because in the description page it does mention ssd1963 in its supported graphic controllers but in the user_settings.h there is no option for SSD1963 in the commented #define

**Comment by lovyan03** [comment]
@Ali-Abdelwdod 
Thanks for reporting this !
I forgot to add the comment from SSD1963.
I've updated the develop branch.

You can use it as follows, please try it.

```
  lgfx::Panel_SSD1963     _panel_instance;
```

**Comment by Ali-Abdelwdod** [comment]
OK. thanks for your fast reply
