### ISSUE TITLE
error when using I2S for parallel

### ISSUE THREAD

**Issue by Ali-Abdelwdod** [lovyan03/LovyanGFX#160]
When I Configure for parallel and uncomment its corresponding statements, in the following statement:
cfg.i2s_port = 1;           

the following error appears:
error: invalid conversion from 'int' to 'i2s_port_t' [-fpermissive]

**Comment by lovyan03** [comment]
@Ali-Abdelwdod 
Try writing it like this.
```
cfg.i2s_port = I2S_NUM_1;
```
