### ISSUE TITLE
Add a built-in GIF decoder

### ISSUE THREAD

**Issue by fsender** [lovyan03/LovyanGFX#165]
I have to use an external GIF decode library to play my GIF files.
I hope you could add a built-in GIF decoder to make it more convenient.

**Comment by lovyan03** [comment]
@fsender 
Thanks for your request !
Are you looking to handle animated GIFs?

**Comment by fsender** [comment]
Yes. I feel like processing animation faster than other GIF decoding libraries.
Also, I'd like to draw some anti-aliased lines, arcs, circles, ellipses, bezier, etc. They should be smoother than normal ones.
You can add an optional parameter to enable anti-aliased shapes or add a new function to enable/disable anti-aliased shapes globally.
