### ISSUE TITLE
Displaying on SH1106 shifted

### ISSUE THREAD

**Issue by johalaoui** [lovyan03/LovyanGFX#177]
Hello @lovyan03 ,

I have encountered this problem:
![20211223_110200](https://user-images.githubusercontent.com/22944000/147225049-615d5730-fb73-477e-8b63-2b3b5b847018.jpg)
After adding `cfg.prefix_len = 3;` it looked like the problem was fixed, but this broke other things instead:
![20211223_110005](https://user-images.githubusercontent.com/22944000/147225310-456695d3-952f-43a8-8f68-a58bab2de8ab.jpg)

Then removed the line previously added and tested different possible fixes seperately:
`cfg.offset_x = 2;`:
![20211223_113626_x2](https://user-images.githubusercontent.com/22944000/147230467-d0c1849d-73ea-458a-b170-010814d398dd.jpg)
`cfg.offset_x = -2;`:
![20211223_113818_x-2](https://user-images.githubusercontent.com/22944000/147230521-16408721-5e41-40b8-bc15-cc665b2652fd.jpg)
`cfg.offset_y = 2;`:
![20211223_114114_y2](https://user-images.githubusercontent.com/22944000/147230616-92e3b499-f81e-43bd-b9a7-f07cf0e017d0.jpg)
`cfg.offset_y = -2;`:
![20211223_114210_y-2](https://user-images.githubusercontent.com/22944000/147230631-2919bfc7-84c8-477c-a600-f0b87188e88d.jpg)
Datasheet: https://www.berrybase.de/en/Pixelpdfdata/Articlepdf/id/8082/onumber/OLED-12864-B
The current configuration is posted below and I would appreciate any help.

Thanks in advance.

```/*
 * LGFX_user_SH1106.hpp
 *  similar to LovyanGFX/src/lgfx_user/LGFX_ESP32_sample.hpp
 *  Created on: Nov 4, 2021
 */

#pragma once

#define LGFX_USE_V1

#include <LovyanGFX.hpp>
#include "pinMapEsp32.h"

class LGFX : public lgfx::LGFX_Device {
  lgfx::Panel_SH110x _panel_instance;
  lgfx::Bus_I2C _bus_instance;

 public:

  LGFX(void) {
    {
      auto cfg = _bus_instance.config();

      cfg.i2c_port = 0;
      cfg.freq_write = 400000;
      cfg.freq_read = 400000;
      cfg.pin_sda = i2c_sda;
      cfg.pin_scl = i2c_scl;
      cfg.i2c_addr = 0x3C;

      _bus_instance.config(cfg);
    }
    _panel_instance.setBus(&_bus_instance);

    {
      auto cfg = _panel_instance.config();

      cfg.memory_width = 128;
      cfg.memory_height = 64;
      cfg.panel_width = 128;
      cfg.panel_height = 64;
      cfg.offset_x = 0;
      cfg.offset_y = 0;

      _panel_instance.config(cfg);
    }
    setPanel(&_panel_instance);
  }
};
```

**Comment by tobozo** [comment]
hey :-)

This display is 132 px, not 128.

Another possibility is to use the SSD1306 driver if you don't mind the missing 4x64 block.

**Comment by johalaoui** [comment]
Hello @tobozo,
I have tried using the SSD1306, but it doesn't show any image at all.
The display output looks like it is shifted by 2 pixels rather than 4.
The U8g2 library does work, but my current work is not based on it and LovyanGFX is faster.
![20211223-132333_U8g2](https://user-images.githubusercontent.com/22944000/147240357-de5ad127-2784-4a69-b97d-a54c65b653db.jpeg)

```
#include <U8g2lib.h>
#include <pinMapEsp32.h>
U8G2_SH1106_128X64_NONAME_F_HW_I2C display(U8G2_R0, /* reset=*/U8X8_PIN_NONE, i2c_scl, i2c_sda);
void setup(void) {
  display.begin();
  display.setFontPosTop();
  display.setFont(u8g2_font_ncenB14_tr);
}

void loop() {
  display.drawStr(0, 0, "Hi");
  display.sendBuffer();
  delay(1000);
}
```

**Comment by tobozo** [comment]
what about this?

```
      cfg.memory_width = 132;
      cfg.memory_height = 64;
      cfg.panel_width = 132;
      cfg.panel_height = 64;
      cfg.offset_x = 2;
      cfg.offset_y = 0;
```

**Comment by johalaoui** [comment]
> what about this?
> 
> ```
>       cfg.memory_width = 132;
>       cfg.memory_height = 64;
>       cfg.panel_width = 132;
>       cfg.panel_height = 64;
>       cfg.offset_x = 2;
>       cfg.offset_y = 0;
> ```

I have tested this with a picture in the first comment.

**Comment by johalaoui** [comment]
> what about this?
> 
> ```
>       cfg.memory_width = 132;
>       cfg.memory_height = 64;
>       cfg.panel_width = 132;
>       cfg.panel_height = 64;
>       cfg.offset_x = 2;
>       cfg.offset_y = 0;
> ```
There is no image.

**Comment by lovyan03** [comment]
@johalaoui @tobozo 
Sorry for the late reply.

memory_width and memory_height : set the sizes supported by the driver IC.
panel_width and panel_height : set the size that can be displayed.

```
cfg.memory_width = 132;
cfg.memory_height = 64;
cfg.panel_width = 128;
cfg.panel_height = 64;
cfg.offset_x = 2;
cfg.offset_y = 0;
```

**Comment by johalaoui** [comment]
> @johalaoui @tobozo Sorry for the late reply.
> 
> memory_width and memory_height : set the sizes supported by the driver IC. panel_width and panel_height : set the size that can be displayed.
> 
> ```
> cfg.memory_width = 132;
> cfg.memory_height = 64;
> cfg.panel_width = 128;
> cfg.panel_height = 64;
> cfg.offset_x = 2;
> cfg.offset_y = 0;
> ```
After this change the display shows this:
![20211223_145637](https://user-images.githubusercontent.com/22944000/147250382-9dbce650-85f2-4127-ba58-4ca47f592ce5.jpg)

**Comment by lovyan03** [comment]
@johalaoui 
umm... 
Then maybe offset_x = 0; is fine...?

**Comment by lovyan03** [comment]
@johalaoui 
Fixed a bug in the develop branch. Please try using this.
I think this is the configuration you can use.

```
cfg.memory_width = 132;
cfg.memory_height = 64;
cfg.panel_width = 128;
cfg.panel_height = 64;
cfg.offset_x = 2;
cfg.offset_y = 0;
```

**Comment by johalaoui** [comment]
Excellent work👍️
It works now as expected. In my case it also works when I only set `cfg.offset_x = 2;`. But I will use your config out of compatibility reasons.

Thank You @lovyan03

![20211224_094305](https://user-images.githubusercontent.com/22944000/147336157-5029a3db-5851-48a1-a7ec-ea386d4fe9c8.jpg)
