### ISSUE TITLE
png draw sub image with wrong result

### ISSUE THREAD

**Issue by dotnfc** [lovyan03/LovyanGFX#195]
i've test the 'drawPng()' with a 10 * 180 PNG file, just want to draw one sub image( 18 * 18 ) to a sprite:

`	
// index => [0, 17]
sp.drawPng(weather_wind_dir, sizeof(weather_wind_dir), 0, 0, 18, 18, 
            0, index * 18, 1, 1, TL_DATUM);  

`
this will get a proper result. but if i change CC_DATUM, the will lead to wrong display, for example:
index = 1, it will show half sub-2 and half sub-3.

am i mis-understand the api paramerter?

**Comment by lovyan03** [comment]
@dotnfc 
Yes, you have misunderstood the specification.
The offset function works for the entire image.
If you want to adjust the drawing position partially, you need to calculate it by yourself.
