### ISSUE TITLE
ESP-IDF & Arduino samples for WT32-SC01 using LVGL8 + LOVYANGFX 

### ISSUE THREAD

**Issue by sukesh-ak** [lovyan03/LovyanGFX#203]
Wanted to take a moment to thank you for the excellent LovyanGFX library!

Device : WT32-SC01 
Display / Touch Drivers : LovyanGFX
Widgets : LVGL 8.x

ESP-IDF => WT32-SC01 + LVGL8 + LOVYANGFX 
https://github.com/sukesh-ak/LVGL8-WT32-SC01-IDF

Arduino => WT32-SC01 + LVGL8 + LOVYANGFX 
https://github.com/sukesh-ak/LVGL8-WT32-SC01-Arduino

**Comment by lovyan03** [comment]
Thank you for the compliment !
