### ISSUE TITLE
About panel HX8357

### ISSUE THREAD

**Issue by JohnTaipei** [lovyan03/LovyanGFX#211]
Hello Sir:
Why can not compile HX8357??

#define LGFX_USE_V1
#include <LovyanGFX.hpp>

class LGFX : public lgfx::LGFX_Device
{
    lgfx::Panel_HX8357      _panel_instance;
    lgfx::Bus_Parallel8 _bus_instance;   // 8ビットパラレルバスのインスタンス (ESP32のみ)

**Comment by lovyan03** [comment]
@JohnTaipei 

Please choose whether the last letter of the alphabet is B or D.

//lgfx::Panel_HX8357B     _panel_instance;
//lgfx::Panel_HX8357D     _panel_instance;

**Comment by JohnTaipei** [comment]
Thank you Sir
I got it
