### ISSUE TITLE
How to use 16bit parallel with ESP32 S3

### ISSUE THREAD

**Issue by uldara1** [lovyan03/LovyanGFX#237]
Hi @lovyan03 i just start with 16bit parallel for ESP S3

but when i add pin d0-d15 it show error 
pls check attached file 
thank you

<img width="1018" alt="Screen Shot 2022-05-12 at 9 40 07 AM" src="https://user-images.githubusercontent.com/22394956/167981451-2ebcbbeb-756f-4f4e-8d31-1d31ce87721d.png">

**Comment by lovyan03** [comment]
@uldara1 
The ESP32-S3 has a new LCD_CAM peripheral in place of I2S.
Therefore, I2S is no longer used and the `i2s_port` setting has been removed, so comment out the line with the error.
Also, if you want to use 16-bit parallel, use `Bus_Parallel16` instead of `Bus_Parallel8`.

**Comment by uldara1** [comment]
@lovyan03 
thank for your support now no error 
unfortunately library not support my display yet  
my display is RM68120
