### ISSUE TITLE
Is the FT5X46 compatible with the FT5X06?

### ISSUE THREAD

**Issue by JaviEM92** [lovyan03/LovyanGFX#260]
hello first of all thanks for the hard work of developing this library for lcd screens.

I want to buy an LCD screen reference DT028CTFT-PTS2 which uses a FT5X46 touch controller I would like to know if this is compatible with the controller already implemented in the library which is the FT5X06 thank you very much. 

product link https://www.digikey.com/es/products/detail/displaytech/DT028CTFT-PTS2/11561141.  Thanks a lot

**Comment by lovyan03** [comment]
hello @JaviEM92 
Yes. It works fine with Touch_FT5x06 class.

**Comment by JaviEM92** [comment]
thank you very much you are great!!!
