### ISSUE TITLE
Example ESP32DeepSleepDisplay.ino uses inexistent Panel_Device#gpio_bl

### ISSUE THREAD

**Issue by marcelstoer** [lovyan03/LovyanGFX#266]
## Environment ( 実行環境 )

- MCU or Board name:  ESP32-WROVER
- Panel Driver IC:    ILI9488
- Bus type:          SPI
- LovyanGFX version:  v0.4.17
- FrameWork version:   ArduinoESP32 v2.0.3
- Build Environment :   PlatformIO
- Operating System:   macOS

## Problem Description ( 問題の内容 )

Compilation of the `ESP32DeepSleepDisplay.ino` code fails as 

> 'struct lgfx::v1::Panel_Device' has no member named 'gpio_bl'

https://github.com/lovyan03/LovyanGFX/blob/3af472568a319bb4c5543f00edc0c30f02770c1a/examples/Advanced/ESP32DeepSleepDisplay/ESP32DeepSleepDisplay.ino#L64

Indeed, https://github.com/lovyan03/LovyanGFX/blob/master/src/lgfx/v1/panel/Panel_Device.hpp#L37 has no `gpio_bl`. However, the v0 version does have it at https://github.com/lovyan03/LovyanGFX/blob/master/src/lgfx/v0/panel/PanelCommon.hpp#L28.

**Comment by lovyan03** [comment]
@marcelstoer 
Thanks for bringing this issue to my attention.
This sample code had not been maintained for some time and was written based on an outdated specification.

Source code modifications were made to the develop branch.
