### ISSUE TITLE
Confused about color handling

### ISSUE THREAD

**Issue by marcelstoer** [lovyan03/LovyanGFX#270]
I have this simple example below. I am confused as to why the rectangle in the lower right corner is blue rather than red. It's as if RGB were interpreted as BGR.

```cpp
#define LGFX_USE_V1
#include <LovyanGFX.hpp>

static LGFX display;

int32_t w, h;
void setup(void) {
  display.init();

  w = display.width();
  h = display.height();

  log_i("Display width: %d, height: %d", w, h);
  log_i("Rotation: %d", display.getRotation());

  int8_t l = 10;
  display.fillRect(0, 0, l, l, TFT_WHITE);
  display.fillRect(w - l, h - l, l, l, TFT_RED);

  display.setTextColor(TFT_WHITE);
  display.setFont(&fonts::FreeSans9pt7b);
  display.drawString("0", 20, 20);
  display.drawString(String(w) + "/" + String(h), w - 70, h - 40);
}
```
![IMG_6203](https://user-images.githubusercontent.com/624195/181123994-daa8ecc6-6e39-4cd3-b61a-5a5cc8d3cb92.jpg)

**Comment by lovyan03** [comment]
You need to adjust the setting items in the panel. `rgb_order`

**Comment by marcelstoer** [comment]
I have `cfg.rgb_order = true;` which I confirmed with `log_i("Color mode RGB: %d", display.panel()->config().rgb_order);`.

> 08:01:01.031 > [I][main.cpp:26] setup(): Color mode RGB: 1

From what I understand i.e. based on the Google translate of the Japanese comments this should give me RGB, no?

**Comment by lovyan03** [comment]
Rewrite and try before asking me questions.

**Comment by marcelstoer** [comment]
Of course I did. I am asking because the code is not clear to me and the comments are in Japanese. I can set `cfg.rgb_order = false;` which gives me red but this is contrary to what I understand from the comments.

It looks like `rgb_order = false` means "do NOT swap red and blue"?

**Comment by lovyan03** [comment]
パネルの仕様によって違うので何とも言えませんね。
