### ISSUE TITLE
Would you support LT7685 SPI mode LCD controller with LovyanGFX?

### ISSUE THREAD

**Issue by CBLeong1985** [lovyan03/LovyanGFX#278]
**Carefully written requests are more likely to be given priority.**
**丁寧に記述された要望は優先して対応される可能性が高くなります。**

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by lovyan03** [comment]
Click on the link below to resubmit your Issue. If it only has a title, I will disregard it.

https://github.com/lovyan03/LovyanGFX/issues/new?assignees=&labels=device+support+request&template=device-support-request-------------.md&title=
