### ISSUE TITLE
The path to ESP-IDF version 5

### ISSUE THREAD

**Issue by martinberlin** [lovyan03/LovyanGFX#282]
It seems the nice people from Espressif has made our lives miserable with some breaking changes:

https://docs.espressif.com/projects/esp-idf/en/latest/esp32/migration-guides/release-5.x/index.html

Most importantly is that the previous GCC version was GCC 8.4.0 (IDF ver < 5).  This has now been upgraded to **GCC 11.2.0 on all targets**.

So far I had also trouble adapting my (mostly SPI) epaper component to build in this [new version of IDF](https://github.com/martinberlin/cale-idf/compare/develop...idf_v5?expand=1). 

This is the list that I get so far when trying to compile Lovyan GFX in **develop** branch and I can help with ideas / testing so it will build also in this version:

- [x] /platforms/esp32/common.hpp:28:10: fatal error: driver/gpio.h: No such file or directory
      This simply because it does not find gpio.h unless  "COMPONENT_REQUIRES driver" is also present in the CMakeLists **idf_component_register**  (easy fix)

- [x] /v1/panel/../Panel.hpp:160:19: error: 'buf' may be used uninitialized [-Werror=maybe-uninitialized]
 This one I'm not sure why it is but I will research a bit more.

- [x] /v1/platforms/esp32/common.hpp:44:95: error: 'esp_timer_get_time' was not declared in this scope (easy fix)
This is simply because it needs:  #include <esp_timer.h>    C header in order to access this function (It seems it was included in prior versions)
I also had to add it in COMPONENT_REQUIRES esp_timer

- [x] /platforms/esp32/common.hpp:47:80: error: 'ets_delay_us' was not declared in this scope
This is one is weird since in previous versions it was defined in rom/ets_sys.h  And it's still there but it seems it won't find it now, will find out...

- [x]  calcClockDiv even though uses size_t to accept any kind of integer type still bumps error when compiling with IDF 5 forcing me to add silly (size_t*) casting   

```
113 |     calcClockDiv((size_t*)&div_a,(size_t*) &div_b, (size_t*)&div_n, &clkcnt, 240*1000*1000, _cfg.freq_write);
      |                                                                     ^~~~~~~
      |                                                                     |
      |                                                                     uint32_t* {aka long unsigned int*}
```

- [x] /esp32/Bus_SPI.cpp:125:17: error: 'spi_bus_get_attr' was not declared in this scope
This one is still not clear for me since driver is already in REQUIRES. Will check if it needs something additional to get it there. But in my opinion it should be already added since is in path: /driver/include/esp_private/spi_common_internal.h  
It's simply like it won't find it under the scope of Bus_SPI. Solved it updating that include to:

```C
#if __has_include(<esp_private/spi_common_internal.h>)
  #include <esp_private/spi_common_internal.h>
#endif
```

- [x] /platforms/esp32/common.hpp:87:92: error: 'GPIO' was not declared in this scope
To solve this in [EPDiy parallel driver](https://github.com/vroland/epdiy/pull/180/files#diff-1d705dd5f1052e7fa91e7278e9d94c963746fccf9951e7a3e63b4f03affdde1a) we added:

```C
// Not sure if both are needed but otherwise GPIO is not found
#if ESP_IDF_VERSION >= ESP_IDF_VERSION_VAL(5, 0, 0)
  #include "hal/gpio_ll.h"
  #include "soc/gpio_struct.h"
#endif
```

Other than that in order to keep on finding out what else needs to be updated I had to add some function aliases in platforms/esp32/common.hpp (Note I tried so far only in esp32 platform)

```C
// Function aliases
auto& ets_delay_us = esp_rom_delay_us;
auto& gpio_pad_select_gpio = esp_rom_gpio_pad_select_gpio;
// auto& gpio_matrix_out = gpio_iomux_out; // Not correct since gpio_matrix_out has an additional 4th param: bool oen_inv
```

Still in the latest [GPIO & RTC documentation](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/peripherals/gpio.html) only gpio_iomux_in / gpio_iomux_out seem to be there, but no **gpio_matrix_*** functions. Or I'm missing something and gpio_matrix_in / out are declared somewhere else ?

Why they changed this knowing it will break most existing code, no idea...

- [ ] /lovyanGFX/src/lgfx/v1/lgfx_filesystem_support.hpp:60:13: error: template-id not allowed for destructor
```
   60 |     virtual ~LGFX_FILESYSTEM_Support<Base>()
      |             ^
```
Some research about this: It seems in GCC11 in any class, U, can have one and only one destructor, which is declared within that class with the name ~U() and accepts exactly no parameters. But a template function specifies a family of functions, where a "family" describes a set containing one or more, with no upper limit on the number of members. So if I see this correctly is not possible to make desctructors in templates like this anymore.

This seems to be the last one when compiling my IT8951 example. Will go through it later.

 Will be updating this with new findings soon. 
 Like always very grateful to have this component. And I would like to make it build and flash also in this new version of IDF.

**Comment by martinberlin** [comment]
Impressive update @lovyan03 thanks a lot!

Only remaining thing that I had to comment in order to get it built was: 

```
../components/lovyanGFX/src/lgfx/v1/lgfx_filesystem_support.hpp: At global scope:
../components/lovyanGFX/src/lgfx/v1/lgfx_filesystem_support.hpp:60:13: error: template-id not allowed for destructor
   60 |     virtual ~LGFX_FILESYSTEM_Support<Base>()
```

I don't get it, now then on GCC 11, you can't add a destructor in a Template?
How to do it then?

**Comment by lovyan03** [comment]
@martinberlin 
Thanks for letting me know!

I removed the destructor from the template class.
Let me know if you still have problems.

**Comment by martinberlin** [comment]
Hi @lovyan03 
Now it builds correctly without any problem in IDF v5. Good work!

**Comment by dizcza** [comment]
I'm facing the same issue. LGFX is a dependency for https://github.com/sukesh-ak/LVGL8-WT32-SC01-IDF and my hands are dirty fixing the LGFX issues regarding ESP-IDF v5.x. I've already fixed the abovementioned problem with `miniz.c`, missing required components, missing `esp_timer.h` includes, but still don't see light at the end of the tunnel.

Should I switch to the develop branch? It looks broken according to CI.

**Comment by lovyan03** [comment]
@dizcza 
I have just readjusted the develop branch. I think it should build now.
There seems to be a build error in IDFv4.3.1 of ESP32-S2, but this should not affect this case.

**Comment by dizcza** [comment]
@lovyan03 
thanks! The developer branch works now with ESP-IDF v5.1-dev-96-gafc6fba7f5-dirty

**Comment by dizcza** [comment]
It outputs a number of annoying warnings though:
```
In file included from /home/dizcza/Projects/Embedded/eclipse-workspace/other/LVGL8-WT32-SC01-IDF/components/LovyanGFX/src/lgfx/v0/panel/Panel_GDEW0154M09.cpp:4:
/home/dizcza/Projects/Embedded/eclipse-workspace/other/LVGL8-WT32-SC01-IDF/components/LovyanGFX/src/lgfx/v0/panel/Panel_GDEW0154M09.hpp: In constructor 'lgfx::v0::Panel_GDEW0154M09::Panel_GDEW0154M09()':
/home/dizcza/Projects/Embedded/eclipse-workspace/other/LVGL8-WT32-SC01-IDF/components/LovyanGFX/src/lgfx/v0/panel/Panel_GDEW0154M09.hpp:52:20: warning: implicitly-declared 'constexpr lgfx::v0::range_rect_t& lgfx::v0::range_rect_t::operator=(const lgfx::v0::range_rect_t&)' is deprecated [-Wdeprecated-copy]
   52 |       _range_new = _range_old;
      |                    ^~~~~~~~~~
In file included from /home/dizcza/Projects/Embedded/eclipse-workspace/other/LVGL8-WT32-SC01-IDF/components/LovyanGFX/src/lgfx/v0/panel/Panel_GDEW0154M09.cpp:1:
/home/dizcza/Projects/Embedded/eclipse-workspace/other/LVGL8-WT32-SC01-IDF/components/LovyanGFX/src/lgfx/v0/panel/../lgfx_common.hpp:1634:5: note: because 'lgfx::v0::range_rect_t' has user-provided 'lgfx::v0::range_rect_t::range_rect_t(const lgfx::v0::range_rect_t&)'
 1634 |     range_rect_t(const range_rect_t& rhs) : horizon(rhs.horizon), vertical(rhs.vertical) {}
      |     ^~~~~~~~~~~~
/home/dizcza/Projects/Embedded/eclipse-workspace/other/LVGL8-WT32-SC01-IDF/components/LovyanGFX/src/lgfx/v0/panel/Panel_GDEW0154M09.cpp: In member function 'virtual void lgfx::v0::Panel_GDEW0154M09::post_init(lgfx::v0::LGFX_Device*, bool)':
/home/dizcza/Projects/Embedded/eclipse-workspace/other/LVGL8-WT32-SC01-IDF/components/LovyanGFX/src/lgfx/v0/panel/Panel_GDEW0154M09.cpp:26:18: warning: implicitly-declared 'constexpr lgfx::v0::range_rect_t& lgfx::v0::range_rect_t::operator=(const lgfx::v0::range_rect_t&)' is deprecated [-Wdeprecated-copy]
   26 |     _range_new = _range_old;
      |                  ^~~~~~~~~~
In file included from /home/dizcza/Projects/Embedded/eclipse-workspace/other/LVGL8-WT32-SC01-IDF/components/LovyanGFX/src/lgfx/v0/panel/Panel_GDEW0154M09.cpp:1:
/home/dizcza/Projects/Embedded/eclipse-workspace/other/LVGL8-WT32-SC01-IDF/components/LovyanGFX/src/lgfx/v0/panel/../lgfx_common.hpp:1634:5: note: because 'lgfx::v0::range_rect_t' has user-provided 'lgfx::v0::range_rect_t::range_rect_t(const lgfx::v0::range_rect_t&)'
 1634 |     range_rect_t(const range_rect_t& rhs) : horizon(rhs.horizon), vertical(rhs.vertical) {}
      |     ^~~~~~~~~~~~
/home/dizcza/Projects/Embedded/eclipse-workspace/other/LVGL8-WT32-SC01-IDF/components/LovyanGFX/src/lgfx/v0/panel/Panel_GDEW0154M09.cpp: In static member function 'static void lgfx::v0::Panel_GDEW0154M09::display(lgfx::v0::PanelCommon*, lgfx::v0::LGFX_Device*, int32_t, int32_t, int32_t, int32_t)':
/home/dizcza/Projects/Embedded/eclipse-workspace/other/LVGL8-WT32-SC01-IDF/components/LovyanGFX/src/lgfx/v0/panel/Panel_GDEW0154M09.cpp:302:26: warning: implicitly-declared 'constexpr lgfx::v0::range_rect_t& lgfx::v0::range_rect_t::operator=(const lgfx::v0::range_rect_t&)' is deprecated [-Wdeprecated-copy]
  302 |     me->_range_old = me->_range_new;
      |                          ^~~~~~~~~~
In file included from /home/dizcza/Projects/Embedded/eclipse-workspace/other/LVGL8-WT32-SC01-IDF/components/LovyanGFX/src/lgfx/v0/panel/Panel_GDEW0154M09.cpp:1:
/home/dizcza/Projects/Embedded/eclipse-workspace/other/LVGL8-WT32-SC01-IDF/components/LovyanGFX/src/lgfx/v0/panel/../lgfx_common.hpp:1634:5: note: because 'lgfx::v0::range_rect_t' has user-provided 'lgfx::v0::range_rect_t::range_rect_t(const lgfx::v0::range_rect_t&)'
 1634 |     range_rect_t(const range_rect_t& rhs) : horizon(rhs.horizon), vertical(rhs.vertical) {}
      |     ^~~~~~~~~~~~
[850/1071] Building CXX object esp-idf/LovyanGFX/CMakeF...df_LovyanGFX.dir/src/lgfx/v0/panel/Panel_IT8951.cpp.obj/home/dizcza/Projects/Embedded/eclipse-workspace/other/LVGL8-WT32-SC01-IDF/components/LovyanGFX/src/lgfx/v0/panel/Panel_IT8951.cpp: In static member function 'static void lgfx::v0::Panel_IT8951::display(lgfx::v0::PanelCommon*, lgfx::v0::LGFX_Device*, int32_t, int32_t, int32_t, int32_t)':
/home/dizcza/Projects/Embedded/eclipse-workspace/other/LVGL8-WT32-SC01-IDF/components/LovyanGFX/src/lgfx/v0/panel/Panel_IT8951.cpp:672:26: warning: implicitly-declared 'constexpr lgfx::v0::range_rect_t& lgfx::v0::range_rect_t::operator=(const lgfx::v0::range_rect_t&)' is deprecated [-Wdeprecated-copy]
  672 |     me->_range_old = me->_range_new;
      |                          ^~~~~~~~~~
In file included from /home/dizcza/Projects/Embedded/eclipse-workspace/other/LVGL8-WT32-SC01-IDF/components/LovyanGFX/src/lgfx/v0/panel/Panel_IT8951.cpp:1:
/home/dizcza/Projects/Embedded/eclipse-workspace/other/LVGL8-WT32-SC01-IDF/components/LovyanGFX/src/lgfx/v0/panel/../lgfx_common.hpp:1634:5: note: because 'lgfx::v0::range_rect_t' has user-provided 'lgfx::v0::range_rect_t::range_rect_t(const lgfx::v0::range_rect_t&)'
 1634 |     range_rect_t(const range_rect_t& rhs) : horizon(rhs.horizon), vertical(rhs.vertical) {}
      |     ^~~~~~~~~~~~
[1065/1071] Building CXX object esp-idf/main/CMakeFiles/__idf_main.dir/main.cpp.objIn file included from /home/dizcza/Projects/Embedded/eclipse-workspace/other/LVGL8-WT32-SC01-IDF/components/lvgl/src/core/lv_obj.h:140,
                 from /home/dizcza/Projects/Embedded/eclipse-workspace/other/LVGL8-WT32-SC01-IDF/components/lvgl/lvgl.h:35,
                 from /home/dizcza/Projects/Embedded/eclipse-workspace/other/LVGL8-WT32-SC01-IDF/main/main.cpp:21:
/home/dizcza/Projects/Embedded/eclipse-workspace/other/LVGL8-WT32-SC01-IDF/components/lvgl/src/core/lv_obj_style.h: In function 'void lv_obj_remove_style_all(_lv_obj_t*)':
/home/dizcza/Projects/Embedded/eclipse-workspace/other/LVGL8-WT32-SC01-IDF/components/lvgl/src/core/lv_obj_style.h:94:48: warning: bitwise operation between different enumeration types '<unnamed enum>' and '<unnamed enum>' is deprecated [-Wdeprecated-enum-enum-conversion]
   94 |     lv_obj_remove_style(obj, NULL, LV_PART_ANY | LV_STATE_ANY);
      |                                    ~~~~~~~~~~~~^~~~~~~~~~~~~~
/home/dizcza/Projects/Embedded/eclipse-workspace/other/LVGL8-WT32-SC01-IDF/main/main.cpp: In function 'void app_main()':
/home/dizcza/Projects/Embedded/eclipse-workspace/other/LVGL8-WT32-SC01-IDF/main/main.cpp:71:35: warning: missing initializer for member 'esp_timer_create_args_t::arg' [-Wmissing-field-initializers]
   71 |             .name = "periodic_gui"};
      |                                   ^
/home/dizcza/Projects/Embedded/eclipse-workspace/other/LVGL8-WT32-SC01-IDF/main/main.cpp:71:35: warning: missing initializer for member 'esp_timer_create_args_t::dispatch_method' [-Wmissing-field-initializers]
/home/dizcza/Projects/Embedded/eclipse-workspace/other/LVGL8-WT32-SC01-IDF/main/main.cpp:71:35: warning: missing initializer for member 'esp_timer_create_args_t::skip_unhandled_events' [-Wmissing-field-initializers]
/home/dizcza/Projects/Embedded/eclipse-workspace/other/LVGL8-WT32-SC01-IDF/main/main.cpp: In function 'void display_flush(lv_disp_drv_t*, const lv_area_t*, lv_color_t*)':
/home/dizcza/Projects/Embedded/eclipse-workspace/other/LVGL8-WT32-SC01-IDF/main/main.cpp:106:19: warning: 'void lgfx::v1::LGFXBase::pushColors(const uint16_t*, int32_t, bool)' is deprecated: use pushPixels [-Wdeprecated-declarations]
  106 |     lcd.pushColors((uint16_t *)&color_p->full, w * h, true);
      |     ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/dizcza/Projects/Embedded/eclipse-workspace/other/LVGL8-WT32-SC01-IDF/components/LovyanGFX/src/lgfx/v1_init.hpp:25,
                 from /home/dizcza/Projects/Embedded/eclipse-workspace/other/LVGL8-WT32-SC01-IDF/components/LovyanGFX/src/LovyanGFX.hpp:31,
                 from /home/dizcza/Projects/Embedded/eclipse-workspace/other/LVGL8-WT32-SC01-IDF/components/LovyanGFX/src/LovyanGFX.h:5,
                 from /home/dizcza/Projects/Embedded/eclipse-workspace/other/LVGL8-WT32-SC01-IDF/main/main.cpp:16:
/home/dizcza/Projects/Embedded/eclipse-workspace/other/LVGL8-WT32-SC01-IDF/components/LovyanGFX/src/lgfx/v1/LGFXBase.hpp:766:43: note: declared here
  766 |     [[deprecated("use pushPixels")]] void pushColors(const uint16_t* data, int32_t len, bool swap) { startWrite(); writePixels(data, len, swap); endWrite(); }
      |                                           ^~~~~~~~~~
```
Something to be fixed on a rainy evening.

**Comment by tobozo** [comment]
`lgfx::v0` should probably be filtered out with esp-idf 5.0, maybe with a conditional `list(REMOVE_ITEM)`in the CMakeLists.txt ?

**Comment by lovyan03** [comment]
I have made the adjustment again. Perhaps this will eliminate the warning.

**Comment by sukesh-ak** [comment]
@lovyan03 
Since IDF 5.0 just got released, do you have any timeline on these updates in release branch?

**Comment by sukesh-ak** [comment]
@tobozo why does it say beta?
IDF 5.0 was released few days ago.

**Comment by tobozo** [comment]
> workflow CI has been updated v5.0-beta1 => v5.0

@sukesh-ak it says v5.0

**Comment by sukesh-ak** [comment]
> > workflow CI has been updated v5.0-beta1 => v5.0
> 
> @sukesh-ak it says v5.0

Sorry for the confusion :)
