### ISSUE TITLE
Request for RA8876 1024x600 support

### ISSUE THREAD

**Issue by iw7dmh** [lovyan03/LovyanGFX#284]
Request for SPI 7"TFT LCD Dislay 1024x600 w/RA8876 OPTL Capacitive Touch Screen - SPI 4 pin too.

https://www.buydisplay.com/spi-7-inch-tft-lcd-dislay-module-1024x600-ra8876-optl-touch-screen-panel

Thank you very much.

**Comment by astorun** [comment]
any update on this?
