### ISSUE TITLE
ESP32-s3 and ILI9481 not working in 8-bit mode

### ISSUE THREAD

**Issue by magicroomy** [lovyan03/LovyanGFX#319]
## Environment ( 実行環境 )

- ESP32 S3 N16R8
- Panel Driver IC:    ILI9481
- Bus type:           Parallel8
- LovyanGFX version:  v0.4.17
- FrameWork version:   Espressif32 5.2.0 ArduinoESP32 v2.0.5
- Build Environment :   PlatformIO
- Operating System:   Windows

### Steps to reproduce ( 再現のための前提条件 )

Please find attached the src.zip and schematics file.

I designed a dedicated PCB to be used.
I also use the 16 bit bus of the same displays with a different 16 bit PCB and this one works. The difference here is the lgfx_config file to use the 16 bit.

To check out, just try the code.
![Schematics](https://user-images.githubusercontent.com/1277583/204133213-7163ca2b-5f4f-4c99-bfed-acca83d73f2a.png)
[src.zip](https://github.com/lovyan03/LovyanGFX/files/10098196/src.zip)

**Comment by lovyan03** [comment]
GPIO33 ~ 37 of ESP32 S3 N16R8 are connected to PSRAM.
![image](https://user-images.githubusercontent.com/42724151/204133682-79674ecf-b280-420b-8e37-dc2e22a7c473.png)

**Comment by magicroomy** [comment]
> GPIO33 ~ 37 of ESP32 S3 N16R8 are connected to PSRAM. ![image](https://user-images.githubusercontent.com/42724151/204133682-79674ecf-b280-420b-8e37-dc2e22a7c473.png)

Thank you for you immediate answer. I did not have the PS RAM on My Radar.
Nevertheless, the only Pins between 33 and 37 I used was for CS and RS. I changed CS to Pin 3 and RS to pin 8, changed my code.. No effect at all I am afraid.
Any other suggestions for me?

BTW. Great Library !!!

**Comment by lovyan03** [comment]
thanks.

```
   cfg.dlen_16bit = true;
```

if you use 8bit parallel. set this parameter to `false`

**Comment by magicroomy** [comment]
>    cfg.dlen_16bit = true;
> ```
> 
> if you use 8bit parallel. set this parameter to `false`

Yeah... thank you ... I overlooked this one. Thought the lgfx::Bus_Parallel8 would be all I needed to do.
Now it works !
