### ISSUE TITLE
Request for MakerFabs ESP32s3 4.3" IPS LCD support

### ISSUE THREAD

**Issue by GroundLevel1** [lovyan03/LovyanGFX#339]
Hello Lovyan

I would like to say thanks and really appreciate all the hard work you have put into creating and maintaining the LovyanGFX Library. I have enjoyed all the great functions and performance it gives, and greatly benefited using it with my MakerFabs 3.5" ESP32s3 TFT displays. I recently obtained a MakerFabs New ESP32s3 4.3" IPS LCD unfortunately it's currently not supported by your LovyanGFX Library, So i would like to please request if possible it be added to your amazing LovyanGFX Library. If needed i can purchase a test display and perform any test and feed back to help.

The 4.3" IPS Display Spec:
ESP32-S3-WROOM-1-N16R8  MCU [LovyanGFX Supported]
16MB Flash and 8MB PSRAM
4.3" IPS TFT
800*480 pixels
GT911 5 Points capacitive touchscreen controller [LovyanGFX Supported]
MakerFabs indicates its Compatible to [ST7262/ST7289] Driver Chip [Not LovyanGFX Supported]   
LCD interface: RGB565

 The main reasons for switching to the 4.3" IPS [ST7262/ST7282] LCD is this is a little larger than the current 3.5" MakerFabs displays and it has a IPS sunlight readable Screen which will be great for my Air-Quality mobile projects. 

Thanks in Advance 
please let me know if i can Help in anyway

Bryan H
Happy New Year! 2023

ESP32-S3 Parallel TFT with Touch 4.3"
Product Page
https://www.makerfabs.com/esp32-s3-parallel-tft-with-touch-4-3-inch.html

Product Wiki
https://www.makerfabs.com/esp32-s3-parallel-tft-with-touch-4-3-inch.html)

Product Github
[[### URL of the store where we can purchase (商品を購入できるURL](https://www.makerfabs.com/esp32-s3-parallel-tft-with-touch-4-3-inch.html)](https://github.com/Makerfabs/ESP32-S3-Parallel-TFT-with-Touch-4.3inch)

Youtube Video
https://www.youtube.com/watch?v=dMVBIOXZ-1I&t=3s

**Comment by zingo** [comment]
Could this use the same display as sunton-esp32-s3-4-3-inch-ips https://www.makerfabs.com/sunton-esp32-s3-4-3-inch-ips-with-touch.html
That board seem to have some files in the repo so those might be worth trying, the two product seems quite similar from screen point of view.

Off topic:
Also thanks for the tip I currently have the sunton device (not running Lovyan yet on it) and was going to get another one as it was so nice but your device is even better as I actually intended to add a RTC to it. So now I don't need to do that :) (and the USB is probably better, I have some problems with the linux serial usb driver used on the sunton)

**Comment by GroundLevel1** [comment]
Hi Zingo
      Thanks for the response and suggestion i will give it a try and give an update on how well it performs. 

I Appreciate the Support
Bryan H

**Comment by GroundLevel1** [comment]
Hello Zingo
  I was able to get the MakerFabs Sunton 4.3" display demos running on the MakerFabs ST7262 4.3" IPS display i had to edit the device set-up config to match that of the ST7262. They do appear to be compatible

Example of the Demo Sketch
[BH-ST7762-PDQgraphicstest.zip](https://github.com/lovyan03/LovyanGFX/files/10463099/BH-ST7762-PDQgraphicstest.zip)

Thanks
Bryan H

**Comment by zingo** [comment]
Great work, and news!
The more I have been thinking about it the more I want to switch to the device for my current(or all?) project :) Now I know I can get it to work with LovyanGFX and might even get out of the box support :) Thanks for checking.
The Sunton 4.3" seem to be out of stock also making it more hassle if other what to join/re-create the project.

**Comment by sukesh-ak** [comment]
@GroundLevel1 Looks like its already done and available as part of the `develop` branch. Did you test it yet?
https://github.com/lovyan03/LovyanGFX/commit/a6701445079d9d8ad0b5793b9147e2d605c9d594

**Comment by GroundLevel1** [comment]
Hello
I wasn't aware  it was either recently or already being supported by
LovyanGFX Lib i will be giving it a test run very soon thanks for the
update and help

Bryan H

**Comment by GroundLevel1** [comment]
Update
I was able to use the LovyanGFX Lib to display Jpeg format images but it had issues with the rotation function and properly displaying the bottom edges of the jpeg images. The other issue is the images would randomly flicker. I didn't have any success with displaying the Png image format. It's good to see that Lovyan is indeed planning on adding this display to the library and is working on it.

Great Work!
Thanks! :)  to All that are involved with this project

Bryan H
GroundLevel1

**Comment by sukesh-ak** [comment]
> Update I was able to use the LovyanGFX Lib to display Jpeg format images but it had issues with the rotation function and properly displaying the bottom edges of the jpeg images. The other issue is the images would randomly flicker. I didn't have any success with displaying the Png image format. It's good to see that Lovyan is indeed planning on adding this display to the library and is working on it.
> 
> Great Work! Thanks! :) to All that are involved with this project
> 
> Bryan H GroundLevel1

Thanks for the update Bryan. My device is on the way and once I get it will update my project to support it.
You can see my project called ESP32-TUX here
https://github.com/sukesh-ak/ESP32-TUX

**Comment by GroundLevel1** [comment]
Update-2
After using a different call function for the Png images, I was  successful in displaying the Png images correctly. I will keep on testing to see if I can resolve the other remaining issues. I really appreciate all who have worked on making LovyanGFX the greatest graphics Library.

Thanks! Sukesh-Ak for the Update and all your Support and hard work

Bryan H
GroundLevel1

**Comment by lovyan03** [comment]
@GroundLevel1 
Hello. I would like to thank you for being my sponsor !

v1.1.5 has been released. Configuration example In the lgfx_user folder.
Please try it.

for 4.3 inch.
https://github.com/lovyan03/LovyanGFX/blob/master/src/lgfx_user/LGFX_ESP32S3_RGB_MakerfabsParallelTFTwithTouch43.h

for square 4.0 inch.
https://github.com/lovyan03/LovyanGFX/blob/master/src/lgfx_user/LGFX_ESP32S3_RGB_MakerfabsParallelTFTwithTouch40.h

**Comment by GroundLevel1** [comment]
Hello Lovyan
  It's great to know that LovyanGFX now supports MF ESP32s3 4.3" Display. I will be looking forward to trying some of the examples and test sketches. 

I really appreciate all the Support and hard work

Thanks!
GroundLevel1
Bryan H

**Comment by GroundLevel1** [comment]
Hi
 I was recently contacted by MakerFabs they indicated they recently tested the LovyanGFX Lib with the 4.3" IPS TFT and indicated it worked fine. They attached this example Graph code for me to try it worked very well.

[ESP32S3_Graph.zip](https://github.com/lovyan03/LovyanGFX/files/10834973/ESP32S3_Graph.zip)

**Comment by sukesh-ak** [comment]
@GroundLevel1 

Just added simple touch portion as well here
https://gist.github.com/sukesh-ak/c8325c4bb7ec3da40f24977526d513f8
