### ISSUE TITLE
Green color in grayscale problem

### ISSUE THREAD

**Issue by gtwht** [lovyan03/LovyanGFX#347]
Hello. 

I found a problem with displaying colors for st7789. this problem is described here: https://forum.arduino.cc/t/problem-with-st7789v-displays-green-value-1-and-every-other-uneven-is-gray/700584/13

 My solution was to add these lines in Panel_ST7789.hpp :

static constexpr uint8_t CMD_RAMCTRL  = 0xB0;
CMD_RAMCTRL, 2, 0x00, 0xF0,  //0xC0
![Без имени-1](https://user-images.githubusercontent.com/93356644/216772638-b0d1493b-173d-4c49-accd-2eb66ba82340.jpg)
![Без имени-2](https://user-images.githubusercontent.com/93356644/216772642-32bab06c-cf60-4b87-96b0-cd9097bf6568.jpg)

**Comment by lovyan03** [comment]
Hello, @gtwht 
Thanks for bringing this information to my attention !
I was totally unaware of this.
I have checked the configuration and confirmed that it works, so I have reflected it in the develop branch.

**Comment by lovyan03** [comment]
@gtwht 
I have released v1.1.5. I believe this Issue has been resolved.
Please try it.

**Comment by gtwht** [comment]
Hey!! I have same green problemn with wt32-sc01 plus  ( Panel_ST7796 )
The solution to the problem is exactly the same.
