### ISSUE TITLE
Example Sketch TFT_graphicstest_PDQ.ino doesnt compile

### ISSUE THREAD

**Issue by Flo082002** [lovyan03/LovyanGFX#364]
**Carefully written Issues are more likely to be given priority.**
**丁寧に記述された報告は優先して対応される可能性が高くなります。**

## Environment ( 実行環境 )

- MCU or Board name:  ESP-WROOM-32
- Panel Driver IC:    ST7735
- Bus type:           SPI
- LovyanGFX version:  1.1.5
- FrameWork version:   Arduino IDE 2.0.3
- Build Environment :   Arduino IDE 2.0.3
- Operating System:   Linux

## Problem Description ( 問題の内容 )
Example Sketch TFT_graphicstest_PDQ.ino doesnt compile

```
exit status 1

Compilation error: 'TFT_eSPI' does not name a type; did you mean 'TWO_PI'?
```

TFT_eSPI is installed and works fine.

**Comment by tobozo** [comment]
hi,

the `TFT_graphicstest_PDQ.ino` is a leftover of old CI tests.
If you're not a project developer you can safely ignore that file and anything in the "test" folder.
