### ISSUE TITLE
What is the value range for setBrightness?

### ISSUE THREAD

**Issue by codegrue** [lovyan03/LovyanGFX#372]
Is it 0-100, 0-256, or some other range? 

The method is not documented to describe this.

**Comment by fvanroie** [comment]
Set the brightness of the backlight in the range 0-255:
https://github.com/lovyan03/LovyanGFX/blob/43f2165607955cd116164765e3950b90fa88644c/examples/HowToUse/1_simple_use/1_simple_use.ino#L77-L78

**Comment by codegrue** [comment]
Thank you.
