### ISSUE TITLE
Compile error for ESP32_C3

### ISSUE THREAD

**Issue by PM04290** [lovyan03/LovyanGFX#373]
**Carefully written Issues are more likely to be given priority.**
**丁寧に記述された報告は優先して対応される可能性が高くなります。**

simple path compile error on ESP32-C3

## Environment ( 実行環境 )

- MCU or Board name:  ESP32-C3
- Panel Driver IC:    ST7735
- Bus type:           SPI
- LovyanGFX version:  1.1.5
- FrameWork version:   ArduinoESP32 v2.0.5
- Build Environment :   ArduinoIDE 1.8.19
- Operating System:   Windows

## Problem Description ( 問題の内容 )

```
D:\Users\Philippe-ASUS\Documents\Arduino\libraries\LovyanGFX\src\lgfx\v1\platforms\esp32\Bus_SPI.cpp:32:10: fatal error: soc/dport_reg.h: No such file or directoryAlternatives for soc/dport_reg.h: []

 #include <soc/dport_reg.h>
ResolveLibrary(soc/dport_reg.h)          ^~~~~~~~~~~~~~~~~

  -> candidates: []compilation terminated.

```
### Code to reproduce this issue ( 再現させるためのコード )

any

**Comment by tobozo** [comment]
hi, thanks for your feedback :+1: 

this is a kown issue, please check https://github.com/lovyan03/LovyanGFX/issues/368 

you can either [patch manually](https://github.com/lovyan03/LovyanGFX/commit/f1a5139134e9c129466b116b0c7a5d03638a01a3) or use the develop branch.
