### ISSUE TITLE
Unable to get correct touch calibration values

### ISSUE THREAD

**Issue by bil7317** [lovyan03/LovyanGFX#378]
## Environment ( 実行環境 )

- MCU or Board name:  [ESP32-Dev Module]
- Panel Driver IC:    [ILI9341]
- Bus type:           [Parallel8]
- LovyanGFX version:  [v0.4.18]
- FrameWork version:   [ArduinoESP32 v2.0.3]
- Build Environment :   [Arduino IDE]
- Operating System:   [Windows]

## Problem Description ( 問題の内容 )
I want to calibrate the touch display but I only get zero instead of those values on the serial monitor.
### Expected Behavior ( 期待される動作 )
It should display the actual touch calibration values.
### Actual Behavior ( 実際の動作 )
I am only getting zeros instead of actual calibration values.

Here is an output image.
![image](https://user-images.githubusercontent.com/53313955/228157086-9beae41b-6794-4e15-8d56-92326e1232c3.png)

### Code to reproduce this issue ( 再現させるためのコード )
You can get the code from URL below.
[https://gist.github.com/bil7317/3aab9ec263544f4e72c06cfadd76b828](GIST)

[GIST](https://gist.github.com/bil7317/3aab9ec263544f4e72c06cfadd76b828).

**Comment by lovyan03** [comment]
```
    uint16_t calibrationData[8];
    display.calibrateTouch(nullptr, ... // BAD
 ```

```
    uint16_t calibrationData[8];
    display.calibrateTouch(calibrationData, ... // GOOD
 ```

**Comment by bil7317** [comment]
Thanks!
