### ISSUE TITLE
WT32-SC01 touch not working in develop branch

### ISSUE THREAD

**Issue by moinmoin-sh** [lovyan03/LovyanGFX#382]
**Carefully written Issues are more likely to be given priority.**
**丁寧に記述された報告は優先して対応される可能性が高くなります。**

## Environment ( 実行環境 )

- MCU or Board name:  WT32-SC01
- Panel Driver IC:    ST7796, touch driver FT5x06
- Bus type:           SPI
- LovyanGFX version: latest develop
- FrameWork version:  framework-arduinoespressif32 @ 3.20007.0 (2.0.7)
- Build Environment :   PlatformIO
- Operating System:   Windows

## Problem Description ( 問題の内容 )
looks something has changed in the develop branch compared to master.
The touch panel for the WT32-SC01 is not working. Compiling the exact same code with the master branch selected works well

### Code to reproduce this issue ( 再現させるためのコード )

```cpp
{
      auto cfg = _touch_instance.config();

      cfg.x_min = 0;
      cfg.x_max = TFT_WIDTH - 1;
      cfg.y_min = 0;
      cfg.y_max = TFT_HEIGHT - 1;
      cfg.pin_int = TOUCH_INT;  //39
      cfg.bus_shared = false;
      cfg.offset_rotation = 0;

      cfg.i2c_port = 1; // I2C_NUM_1;
      cfg.i2c_addr = 0x38;
      cfg.pin_sda = TOUCH_SDA;  //18
      cfg.pin_scl = TOUCH_SCL;  //19
      cfg.freq = 400000;

      _touch_instance.config(cfg);
      _panel_instance.setTouch(&_touch_instance);
    }

```

**Comment by moinmoin-sh** [comment]
Additional info:
I can confirm, that the same code (using the same touch panel type) is running on
- WT32-SC01-PLUS
- WT32S3-86V (ZX3D95CE01S)

with the develop branch.

Only the WT32-SC01  (non plus) shows the issue. This is the only panel driven by the SPI bus.

**Comment by tobozo** [comment]
> the same touch panel type

do you mean that type ? please provide a touch driver name, the specs sheet isn't very informative :wink: 

![image](https://user-images.githubusercontent.com/1893754/229285815-bc4e1a94-e49d-41ba-ac4c-0ed4bbd9cfc6.png)

I had some issues with M5Core2 touch panel too (FT5x06), the serial console what showing a lot of i2c error messages while the touch was operated.

And switching back to master branch solved the issue, so if you're not using the same FT5x06 driver, maybe it's related to I2C bus?

**Comment by moinmoin-sh** [comment]
Oh, yes, sorry I should have mentioned it.

All devices are using the same touch driver FT5x06

**Comment by tobozo** [comment]
thanks for narrowing this down, the issue seems related to [this commit](https://github.com/lovyan03/LovyanGFX/commit/6b4701adc14d0b6e06493a2314e619f70006190b#diff-ead90fbaf78300e56179961d9a0234927eebe910bf11301de9e7a132c255f173)

[![image](https://user-images.githubusercontent.com/1893754/229293872-257d5579-306e-4619-bf3b-b5f5506c434e.png)](https://github.com/lovyan03/LovyanGFX/blob/develop/src/lgfx/v1/platforms/esp32/common.cpp#L1179)

@lovyan03 this fixes the `i2c read error : read timeout` issue with M5Core2 touch, I hope it doesn't break the last changes with UnitGlass and SSD1306 :sweat: 

```cpp

        if( last_nack ) {
          int cmdidx = 0;
          if (len > 1) {
            i2c_set_cmd(dev, cmdidx++, i2c_cmd_read, len - 1);
          }
          i2c_set_cmd(dev, cmdidx++, i2c_cmd_read, 1, (last_nack && length == 0));
          i2c_set_cmd(dev, cmdidx, i2c_cmd_end, 0);
        } else {
          i2c_set_cmd(dev, 0, i2c_cmd_read, len);
          i2c_set_cmd(dev, 1, i2c_cmd_end, 0);
        }

```

**Comment by moinmoin-sh** [comment]
I applied your fix locally to `common.cpp` and the touch panel is working now!
Looks good for me. (did just a quick test)
Thanks for looking into this issue!

![grafik](https://user-images.githubusercontent.com/53935853/229298560-732c7984-d85a-4ca7-a093-dd54600f1a48.png)

**Comment by lovyan03** [comment]
@moinmoin-sh @tobozo 
Thanks for letting me know about this issue !
I have fixed the develop branch, please try it and see.

**Comment by moinmoin-sh** [comment]
I switched to your actual `develop `branch and can confirm, that the touch panel in the WT32-SC01 is working now.
Thanks for your work.

**Comment by tobozo** [comment]
yup, works for me too
