### ISSUE TITLE
split LGFX_AutoDetect_ESP32S3.hpp

### ISSUE THREAD

**Issue by erazor83** [lovyan03/LovyanGFX#403]
Hi lov,

any plans to split the header files into separate files and merge them via includes?

I think it might get very messy if one tries to add new devices.

**Comment by lovyan03** [comment]
Hello, @erazor83 
Yes, I agree that the current board auto-detection specification makes the task of adding more board types inconvenient.
Ideally, users should be able to add their own local configuration examples to auto-detection.
I would like to do that in a simple and generic way, but have not come up with a good idea at this time.
