### ISSUE TITLE
How to display a bitmap by an const uint8_t array? using RGB565 on M5Core2 in DMA mode

### ISSUE THREAD

**Issue by WangYifa** [lovyan03/LovyanGFX#43]

**Comment by WangYifa** [comment]
In DMA mode

**Comment by lovyan03** [comment]
```
lcd.pushImageDMA( x, y, w, h, (uint16_t*)data);
```

**Comment by lovyan03** [comment]
The "pushImageDMA" function transfers the argument data to DMA.
The "pushImage" function transfers the argument data to a buffer and then uses a DMA transfer internally.
If the data is in flash memory, pushImageDMA transfer is not available.

**Comment by WangYifa** [comment]
Can I use psRAM memory for DMA?

**Comment by lovyan03** [comment]
no.
 PSRAM can't DMA
