### ISSUE TITLE
Compile error for M5 coreink  'LGFX' does not name a type

### ISSUE THREAD

**Issue by linxcow** [lovyan03/LovyanGFX#440]
I get following errr when trying one of the examples

`'LGFX' does not name a type`

I changed to following snippet to select coreink

            #include "M5CoreInk.h"
            
            #define LGFX_M5STACK_COREINK // M5Stack CoreInk
            #include <LovyanGFX.hpp>
            
            Ink_Sprite InkPageSprite(&M5.M5Ink);
            
            static LGFX lcd;

Am i forgetting something?

Info :
Arduino ide 1.8.19
M5 coreink
installed library from within IDE
Windows 10

**Comment by lovyan03** [comment]
#include <LGFX_AUTODETECT.hpp>
