### ISSUE TITLE
compatibility error with ESP-IDF

### ISSUE THREAD

**Issue by leonardokucarz** [lovyan03/LovyanGFX#443]
- MCU or Board name:  [ESP-WROOM-32]
- LovyanGFX version:  [latest develop]
- FrameWork version:   [ESP-IDF v4.4]
- Build Environment:   [VS Code]
- Operating System:   [Windows]

## Problem Description ( 

When I build the project with the LovyanGFX Library, many problems appear, I don't know if there is some configuration that I didn't do correctly, but I'm lost and I don't know what to do.

![image](https://github.com/lovyan03/LovyanGFX/assets/85085056/1c0b4e5d-6226-4d7e-bf67-3421a31ae2d8)

)

```cpp
// the code should be wrapped in the ```cpp tag so that it will be displayed better.
#include "esp_log.h"

void app_main()
{
//I don´t put any code only the librarie
}

```

**Comment by lovyan03** [comment]
https://github.com/lovyan03/LovyanGFX/issues/173
