### ISSUE TITLE
What is the maximum support for the SPI clock for refresh screen？（M5Core2 & TTGO-Watch）

### ISSUE THREAD

**Issue by WangYifa** [lovyan03/LovyanGFX#45]

**Comment by lovyan03** [comment]
T-Watch : 80MHz freq_write and 80MHz freq_fill .
M5Core2 : 40MHz freq_write and 40MHz freq_fill .
You can also specify 80 MHz for freq_fill, but sometimes it leaves garbage in the drawing.
