### ISSUE TITLE
Incorrect character alignment at drawChar

### ISSUE THREAD

**Issue by yamamaya** [lovyan03/LovyanGFX#46]
Those characters are not aligned correctly.

canvas.setTextFont( &fonts::FreeMonoBold18pt7b );
canvas.setTextDatum( textdatum_t::top_left );
canvas.drawChar( '0', 50, 2 );
canvas.setTextFont( &fonts::Font4 );
canvas.drawChar( '0', 70, 2 );

**Comment by lovyan03** [comment]
@yamamaya 
Thank you for reporting this issue !

The following functions are affected by textdatum.
・Functions of the "drawString" family.
・Functions of the "print" family. (Vertical direction only)
It has no effect on drawChar.

And the GFX font is based on a baseline of reference coordinates. This is based on the specifications of AdafruitGFX and is inherited by LovyanGFX.

https://learn.adafruit.com/adafruit-gfx-graphics-library/using-fonts

I recommend that you use "print" or "drawString" even if you only want to output a single character.

**Comment by yamamaya** [comment]
Thank you for your advice!
