### ISSUE TITLE
ESP32-S3 unable to verify code in example librarys

### ISSUE THREAD

**Issue by JandGprojects** [lovyan03/LovyanGFX#462]
「LGFX」が型に名前を付けていないというメッセージが表示され、ライブラリの例が機能しないという問題が発生しています。
 静的LGFX液晶;
Environment

- MCU or Board name:  ESP32-S3
- Panel Driver IC:    ST7796
- Bus type:           [SPI|I2C|Parallel8|Parallel16|other]
- LovyanGFX version:  latest develop
- FrameWork version:   [ArduinoESP32 v2.0.3
- Build Environment:   ArduinoIDE
- Operating System:   Windows

Steps to reproduce

例内の任意のスプライトを開いて確認してみます

![image](https://github.com/lovyan03/LovyanGFX/assets/147950620/9c2e48f5-0468-4aae-8c76-7f6923347898)

コードはライブラリのスプライトセクションの例にあります

**Comment by lovyan03** [comment]
The LGFX type is either created by the user or is the result of AutoDetect.
If you are not using AutoDetect, you must provide your own LGFX type.
