### ISSUE TITLE
WT32 SC-01 Plus - function for display sleep and wakeup after touch

### ISSUE THREAD

**Issue by Jusufs** [lovyan03/LovyanGFX#476]
Hi,
is it possible to use/program this feature please ?
After few seconds the display should use lcd.clear(TFT_BLACK) function to be in sleep mode.
After touch on panel, display should be wake up an display void loop() screen.
Thanks for answer.

**Comment by erazor83** [comment]
I think you should do this in your firmware. I've done it with lvgl and am checking if there were any input timeouts.
