### ISSUE TITLE
Is there any support font has msaa function or Anti-aliasing like lvgl’s fonts

### ISSUE THREAD

**Issue by leodefpv** [lovyan03/LovyanGFX#481]
hi 
    Your lib looks very great and easy to use.
    I think your lib is faster than lvgl in mcu,such as esp32 S3.
     I want to use this lib to drive a lcd through rgb565 signal @640X480.but lvgl only has low fps of this situation.
    In my project it’s not need complex functions of lvgl ,but I need display fonts smooth and good.
  So is there has any font support msaa or anti aliasing like lvgl’s fonts?
Thank you

**Carefully written requests are more likely to be given priority.**
**丁寧に記述された要望は優先して対応される可能性が高くなります。**

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by qiqiji** [comment]
FYI:
https://github.com/lovyan03/LovyanGFX/discussions/321
https://wiki.seeedstudio.com/Wio-Terminal-LCD-Anti-aliased-Fonts/#configuring-the-lcd-library

use vlw font as array (static const uint8_t my_VLW_font[] PROGMEM  = {} ) or save them into sd card then use like this

//sprite.loadFont(my_VLW_font);
sprite.loadFont( "/my_VLW_font.vlw", SPIFFS);
sprite.println("PRND1234567890");
sprite.unloadFont();
