### ISSUE TITLE
DrawJpgFile from SD

### ISSUE THREAD

**Issue by Julien83** [lovyan03/LovyanGFX#488]
Hello when i try to draw jpg from SD card by this line 

static LGFX lcd; 
lcd.drawJpgFile(SD, "/test.jpg");

i have this error 

 no matching function for call to 'lgfx::v1::LGFX::drawJpgFile(fs::SDFS&, const char [10])'
   lcd.drawJpgFile(SD, "/test.jpg");

Can you help me ?

**Comment by tobozo** [comment]
hi,

make sure to include `<SD.h>` **before** `<LovyanGFX.hpp>`
