### ISSUE TITLE
Flag to disable SDL

### ISSUE THREAD

**Issue by jp-bennett** [lovyan03/LovyanGFX#501]
This is related to my previous work, #484 . I've discovered that when building our binary, if the SDL-devel packages are found, this library tries to include SDL support as well as arduino_default. Edit: Which breaks compilation, complaining about multiple definitions. It would be great to be able to define a build flag like LG_DISABLE_SDL so none of that code fires off.

**Comment by lovyan03** [comment]
あなたの環境を知らないので何が問題なのか私にはわからない。
パッケージを含めなければ良いだけではないのですか？

**Comment by jp-bennett** [comment]
@lovyan03 It looks like this library is actively looking for the SDL package. The only way I could get working compilation is to uninstall the SDL2-devel package. Admittedly our environment is a bit odd.

I'll try to produce a working patch in the coming days to demonstrate what I mean.

**Comment by lovyan03** [comment]
もう一度言いますが、私はあなたの環境がわからない
OSは ?  Windows ? macOS ?
開発環境は ? ArduinoIDE ? VSCode ?

基本的にマイコン用にビルドすることを想定しているので、
VSCode+PlatformIOやArduinoIDEなら何も問題は起きないはずです。
SDLがあることでなぜ困るのか状況がわかりません。

**Comment by jp-bennett** [comment]
Compiling on Linux, PlatformIO+VScode, using the Portduino framework to take PlatformIO code and produce a native binary.

Simple to replicate. Make sure the libsdl2-dev package is installed. (and libyaml-cpp-dev libgpiod-dev libbluetooth-dev)
Grab the native-unity branch at https://github.com/meshtastic/firmware/tree/native-unity. In platformIO, select the native target, and build.

**Comment by lovyan03** [comment]
あぁ、あなたは SDLではなくPortduino と組み合わせて使いたいのですね？
つまり Nativeビルドを使用するが、 SDLは使わずに Portduinoで動かしたいんですね？

私はその情報をいま初めて聞いた。それが最も重要な前提情報です。

**Comment by jp-bennett** [comment]
Sorry to leave out that important detail. Yes, we are doing native builds, and talking to real SPI and I2C hardware. It wouldn't be a problem to also have SDL support, but that currently breaks compilation.

**Comment by lovyan03** [comment]
I just found out about Portduino and thought it would be useful.

In that case, if you use the Native build, it would be convenient if you could run LovyanGFX on both Portduino and SDL.
In my opinion, it is necessary to be able to use both at the same time depending on how the user code is written, rather than relying on compile switches.

For now, I'll look into Portduino.

**Comment by lovyan03** [comment]
Portduinoを動かす方法が良くわからない。
前提条件がいろいろあるように思うが環境を整えるのが非常に面倒に思います

**Comment by jp-bennett** [comment]
It's a bit of a pain to use. https://github.com/meshtastic/platform-native is the intended way to do it. Though the easiest starting point for testing is Meshtastic.

**Comment by lovyan03** [comment]
私はWindowsとmacOSを使っていますが、そもそもPortduinoがLinuxにしか対応していないように見えます。

**Comment by lovyan03** [comment]
I updated the develop branch. This will exclude SDL from being built if the define constant ARDUINO exists.
