### ISSUE TITLE
Request for support of ST7262 RGB LCD 800x600 panel

### ISSUE THREAD

**Issue by sukesh-ak** [lovyan03/LovyanGFX#502]
**Carefully written requests are more likely to be given priority.**
**丁寧に記述された要望は優先して対応される可能性が高くなります。**
Request for support of ST7262 RGB LCD 800x600 panel

### Device Name (デバイスの名称・型番等)
Waveshare ESP32-S3-Touch-LCD-4.3

### URL of Device Specifications document (仕様書等のURL)
https://www.waveshare.com/wiki/ESP32-S3-Touch-LCD-4.3

### URL of the store where we can purchase (商品を購入できるURL)
https://www.waveshare.com/esp32-s3-touch-lcd-4.3.htm

**Comment by janick** [comment]
Existing implementation that maybe could be contributed? https://github.com/lovyan03/LovyanGFX/issues/240
