### ISSUE TITLE
in clocksample how do I set the clock time correctly

### ISSUE THREAD

**Issue by cohen-sydney** [lovyan03/LovyanGFX#509]
**Carefully written Issues are more likely to be given priority.**
**丁寧に記述された報告は優先して対応される可能性が高くなります。**

## Environment ( 実行環境 )

- MCU or Board name:  [ESP-WROOM-32|ESP32-S3-BOX|M5Stack|WioTerminal|RPi2040|other]
- Panel Driver IC:    [ILI9341|SSD1963|ST7796|other]
- Bus type:           [SPI|I2C|Parallel8|Parallel16|other]
- LovyanGFX version:  [v0.4.17|latest develop|other]
- FrameWork version:   [ArduinoESP32 v2.0.3|ESP-IDF v4.4|other]
- Build Environment:   [ArduinoIDE|PlatformIO|Eclipse|other]
- Operating System:   [Windows|Linux|macOS]

## Problem Description ( 問題の内容 )

The clock does not show the correct time. is there somewhere in your code to set that or can you add to get the time form the RTC as I have a M5CoreS3??

### Steps to reproduce ( 再現のための前提条件 )

1. step1
2. ...

// If possible, attach a picture of your setup/wiring here.

### Code to reproduce this issue ( 再現させるためのコード )

**Please submit complete source code that can reproduce your problem.**
**あなたの問題を再現できる完全なソースコードを提示してください。**

```cpp
// the code should be wrapped in the ```cpp tag so that it will be displayed better.
#include "esp_log.h"

void app_main()
{

}

```
// If your code is longer than 30 lines, [GIST](https://gist.github.com) is preferred.

**Comment by lovyan03** [comment]
これはグラフィックライブラリの表示サンプルです。
正確な時刻を表示するサンプルではありません。必要に応じてご自分で時刻を取得してください。
