### ISSUE TITLE
Image Convertor for SH1107 OLED

### ISSUE THREAD

**Issue by PDE-Paul** [lovyan03/LovyanGFX#516]
Hi,

Is there a recommended Windows based free Image Convertor (that creates a .h file)?

I am using a custom ESP32 16MB design, communicating with a 1.5 inch SH1107 WaveShare OLED over I2C, all good on initialization, printing text and drawing shapes.

I now wish to display a monochrome "splash" image for a couple seconds after power up but I cannot find a solution to my request. Also there is no example for displaying an image, I don't want to use Sprites.

Any suggestions will be most appreciated. 

Kind Regards
Paul Brink

**Comment by mhaberler** [comment]
you might have a look at https://github.com/lvgl/lvgl/blob/master/scripts/LVGLImage.py

**Comment by PDE-Paul** [comment]
Thank you
