### ISSUE TITLE
ESP32S3

### ISSUE THREAD

**Issue by UnNamedRUS** [lovyan03/LovyanGFX#523]
https://github.com/lovyan03/LovyanGFX/blame/0cabacdb15e730168339faffe3c6392ea3e81f27/src/lgfx/v1/platforms/esp32/common.cpp#L646

**(&dev->comd0)[index].val = cmd_val;**
The project will not be assembled in this form.

**(&dev->comd[0])[index].val = cmd_val;**
And that’s how it all works.

**Comment by lovyan03** [comment]
https://github.com/lovyan03/LovyanGFX/issues/438

**Comment by tobozo** [comment]
bump

[esp-idf 5.2 is now officially the latest release](https://github.com/espressif/esp-idf/releases/tag/v5.2).

Some macros needed to be adjusted in LovyanGFX source tree to fix the compilation errors, the changes are available on the [`develop`](https://github.com/lovyan03/LovyanGFX/tree/develop) branch

![image](https://github.com/lovyan03/LovyanGFX/assets/1893754/11ffdcbd-3243-4451-b464-aed047642c3a)
