### ISSUE TITLE
drawJPG does not work

### ISSUE THREAD

**Issue by daverathbone** [lovyan03/LovyanGFX#533]
## Environment ( 実行環境 )

- MCU or Board name:  [ESP-WROOM-32r]
- Panel Driver IC:    [ILI9488]
- Bus type:           [SPI]
- LovyanGFX version:  [latest develop]
- FrameWork version:   |ESP-IDF v5.0]
- Build Environment:   [Visual Studio Code IDE]
- Operating System:   [ ESP32 IDF / FREERTOS Via Windows 11]

## Problem Description ( 問題の内容 )
My code works for BMP and PNG but Not JPG

### Expected Behavior ( 期待される動作 )
Should take buffer of JPEG file and convert to image
Q) Is the JPEG decoder built in to your code?

### Actual Behavior ( 実際の動作 )
No error but blank on  for JPG screen others text is displayed

### Steps to reproduce ( 再現のための前提条件 )
step 1
```cpp
  lcd.drawBmp(buffer, fileSize, x, y,0, 0, 0, 0, scalex, scaley);   //  works
```
Step 2
```cpp
  lcd.drawPng(buffer, fileSize, x, y,0, 0, 0, 0, scalex, scaley);   // works
```
Step 3
```cpp
  lcd.drawJpg(buffer, fileSize, x, y,0, 0, 0, 0, scalex, scaley);  // Does not work
```

// If possible, attach a picture of your setup/wiring here.
The display has text as well  that works but no image if jpg

```cpp
// main text underlogo
lcd.setCursor(0, 128);
lcd.setTextColor(TFT_GREEN);	
lcd.setFont( &fonts::FreeMonoBold9pt7b);
lcd.println("Select settings with OK button (Not Fitted)");
lcd.println("");
```

### Code to reproduce this issue ( 再現させるためのコード )
```cpp
// place JPG image from file at x,y and adjust scale
void displayJPG(const char *filename, int32_t x, int32_t y, float scalex , float scaley) {
    
        FILE *file = fopen(filename, "r");
        if (!file) {
            ESP_LOGE(TAG, "Failed to open file for reading");
            return;
        }

        fseek(file, 0, SEEK_END);
        long fileSize = ftell(file);
        fseek(file, 0, SEEK_SET);

        uint8_t *buffer = (uint8_t *)malloc(fileSize);
        if (!buffer) {
            ESP_LOGE(TAG, "Failed to allocate memory for file content");
            fclose(file);
            return;
        }

        size_t bytesRead = fread(buffer, 1, fileSize, file);
        if (bytesRead != fileSize) {
            ESP_LOGE(TAG, "Failed to read the file into buffer");
            free(buffer);
            fclose(file);
            return;
        }

        fclose(file);

        lcd.startWrite(); 
        lcd.drawJpg(buffer, fileSize, x, y,0, 0, 0, 0, scalex, scaley);
        lcd.endWrite();  

        free(buffer);
    }

```
**Please submit complete source code that can reproduce your problem.**
**あなたの問題を再現できる完全なソースコードを提示してください。**
 Program is to large but you have the code

**Comment by lovyan03** [comment]
Progressive JPEG is not supported. Please check the JPEG data specifications.

**Comment by daverathbone** [comment]
What JPEG data specification is used if not Progressive JPEG ?

**Comment by lovyan03** [comment]
I don't know the details, but drawJpg is working for me.

**Comment by daverathbone** [comment]
My jpg is just from Windows Paint.net. how have you made your JPG's?

**Comment by lovyan03** [comment]
find out for yourself

**Comment by lovyan03** [comment]
> Progressive is the normal JPG used in 89% of most applications today.

It is difficult to support progressive JPG with a microcontroller with little memory. Try it yourself.
