### ISSUE TITLE
drawEllipseとfillEllipseの、rxとryの一方だけが0のときの挙動について

### ISSUE THREAD

**Issue by matsuura-h** [lovyan03/LovyanGFX#544]
素晴らしいライブラリの公開ありがとうございます。

## Environment ( 実行環境 )
- LovyanGFX version:  githubの最新版

## Problem Description ( 問題の内容 )
冒頭のrx, ryがゼロのときの処理ですが、線を引く処理の第3引数についてrx, ryが逆ではないでしょうか？
    if (ry == 0) {
      drawFastHLine(x - rx, y, (ry << 2) + 1);
      return;
    }
    if (rx == 0) {
      drawFastVLine(x, y - ry, (rx << 2) + 1);
      return;
    }

本来の意図として、例えばryが0のときは、横幅がrxの２倍+1の横線を表示するほうがよいのでは？と考えています。
ご検討お願いいたします。

**Comment by lovyan03** [comment]
@matsuura-h 
情報ありがとうございます！これはうっかりミスですね…修正します。
お知らせくださって助かりました。

**Comment by matsuura-h** [comment]
@lovyan03 
ご確認ありがとうございます。
修正いただいたソースも拝見いたしました。
本件、Closeとさせていただきます。
