### ISSUE TITLE
Freeze using tft.getTouch(...) with a FT5x06 I2C capacitive touch screen

### ISSUE THREAD

**Issue by paxo-project** [lovyan03/LovyanGFX#545]
I'm using capacitive touch screen (i2C) with Touch_FT5x06, and after a certain time, it freeze:

```
[146279][V][common.cpp:1371] readBytes(): [LGFX] i2c read error : ack wait
[192011][W][common.cpp:1402] readBytes(): [LGFX] i2c read error : read timeout
```

## Environment ( 実行環境 )

- MCU or Board name:  ESP32 WROVER B
- Panel Driver IC:   ILI9488
- Bus type:          I2C (touch)
- LovyanGFX version:  lastest on platformio
- FrameWork version:   ArduinoESP32
- Build Environment:   PlatformIO
- Operating System:  Linux

## Problem Description ( 問題の内容 )
Freeze when using 
```
lcd->getTouch(&tx, &ty);
```

It doen't seems to be a deep problem, but if you need more details ask me.

**Comment by tobozo** [comment]
bump

some changes were applied to the FT5x06 driver on the `develop` branch, I'm not sure it will address the bus issues you're experiencing (could be caused by another device on the same bus) but it's worth a shot;  feel free to reopen the issue if it didn't solve it
