### ISSUE TITLE
Support for MakerFab 2.1 inch round MaTouch ESP32-S3 based controller

### ISSUE THREAD

**Issue by kevinlieb** [lovyan03/LovyanGFX#548]
**Carefully written requests are more likely to be given priority.**
I would like support for this new round display with dial control

This code works for init of Arduino GFX:
Arduino_DataBus *bus = new Arduino_SWSPI(
    GFX_NOT_DEFINED /* DC */, 1 /* CS */,
    46 /* SCK */, 0 /* MOSI */, GFX_NOT_DEFINED /* MISO */);

Arduino_ESP32RGBPanel *rgbpanel = new Arduino_ESP32RGBPanel(
    2 /* DE */, 42/* VSYNC */, 3 /* HSYNC */, 45 /* PCLK */,
    4 /* R0 */, 41 /* R1 */, 5 /* R2 */, 40 /* R3 */, 6 /* R4 */,
    39 /* G0/P22 */, 7 /* G1/P23 */, 47 /* G2/P24 */, 8 /* G3/P25 */, 48 /* G4/P26 */, 9 /* G5 */,
    11 /* B0 */, 15 /* B1 */, 12 /* B2 */, 16 /* B3 */, 21 /* B4 */,
    1 /* hsync_polarity */, 10 /* hsync_front_porch */, 8 /* hsync_pulse_width */, 50 /* hsync_back_porch */,
    1 /* vsync_polarity */, 10 /* vsync_front_porch */, 8 /* vsync_pulse_width */, 20 /* vsync_back_porch */);

Arduino_RGB_Display *gfx = new Arduino_RGB_Display(
    480 /* width */, 480 /* height */, rgbpanel, 0 /* rotation */, true /* auto_flush */,
    bus, GFX_NOT_DEFINED /* RST */, st7701_type5_init_operations, sizeof(st7701_type5_init_operations));

### Device Name (デバイスの名称・型番等)
MaTouch ESP32-S3 Rotary IPS Display with Touch 2.1“ ST7701

### URL of Device Specifications document (仕様書等のURL)
https://wiki.makerfabs.com/MaTouch_ESP32_S3_2.1_Rotary_TFT_with_Touch.html

### URL of the store where we can purchase (商品を購入できるURL)
https://www.makerfabs.com/matouch-esp32-s3-rotary-ips-display-with-touch-2-1-st7701.html

Thanks in advance!

**Comment by tobozo** [comment]
hi,

please refer to the many [user contributions](https://github.com/lovyan03/LovyanGFX/tree/master/src/lgfx_user) to produce your own configuration file.

pull requests are welcome :wink:
