### ISSUE TITLE
LilyGo AMOLED Series

### ISSUE THREAD

**Issue by Starbane** [lovyan03/LovyanGFX#549]
**Carefully written requests are more likely to be given priority.**
**丁寧に記述された要望は優先して対応される可能性が高くなります。**

**Is your feature request related to a problem? Please describe.**

There are no native support for:
LilyGo AMOLED 1.47 inch
LilyGo AMOLED 1.91 inch
LilyGo AMOLED 2.41 inch

I was hoping to use LGFX_Sprite to draw, and bit bang it to the display. The possibility to create a LGFX_Sprite without having configured LovyanGFX fully would benefit not only mentioned boards but all boards without native support. Hence, enabling more developers to choose LovyanGFX as a drawing solution for their projects.

**Describe the solution you'd like**

Create the possibility to create and use a LGFX_Sprite as a drawing canvas without fully configuring LovyanGFX, in best scenario no configuration except perhaps bbp.

**Describe alternatives you've considered**

LilyGo supply support for bit banging a void*/len structure so TFT_eSPI defaults nicely so their TFT_eSprite is usable out of the box but it is slower drawing than LovyanGFX.

**Additional context**

The display chips LilyGo chose for the boards have no drawing capabilities other than bit banging a region to display memory, but does rather good and in a speedy manner as well, due to QSPI connection between host and display.

**Comment by tobozo** [comment]
closing this as duplicate with #547 please keep everything related to LilyGo AMOLED in the same post
