### ISSUE TITLE
Add M5Stack_Fire

### ISSUE THREAD

**Issue by PaulskPt** [lovyan03/LovyanGFX#568]
**Carefully written requests are more likely to be given priority.**
**丁寧に記述された要望は優先して対応される可能性が高くなります。**
Would appreciate if you add support for the M5Stack Fire device

### Device Name (デバイスの名称・型番等)
M5Stack Fire

### URL of Device Specifications document (仕様書等のURL)
https://docs.m5stack.com/en/core/fire_v2.6

### URL of the store where we can purchase (商品を購入できるURL)
https://docs.m5stack.com/en/core/fire_v2.6
https://docs.m5stack.com/en/core/fire_v2.7
https://docs.m5stack.com/en/core/fire

Plase add this device to your file:
https://github.com/lovyan03/LovyanGFX/src/lgfx/boards.hpp

**Comment by tobozo** [comment]
hi,

from a panel point of view, M5Stack Fire is just a variant of M5Stack basic core

https://github.com/lovyan03/LovyanGFX/blob/master/examples/HowToUse/1_simple_use/1_simple_use.ino#L7 

closing this as not an issue
