### ISSUE TITLE
tft.getTouch(&touchX, &touchY); freeze loop()

### ISSUE THREAD

**Issue by Red-Owl** [lovyan03/LovyanGFX#580]
**Carefully written Issues are more likely to be given priority.**
**丁寧に記述された報告は優先して対応される可能性が高くなります。**

## Environment ( 実行環境 )

- MCU or Board name:  wt32-sc01-plus
- Panel Driver IC:   ST7796UI
- Bus type:          Parallel8
- LovyanGFX version:  LovyanGFX@1.1.12
- FrameWork version:   ArduinoESP32
- Build Environment:   PlatformIO
- Operating System:   Windows

## Problem Description ( 問題の内容 )
freeze loop()
; FT6336U         I2C   single touch
### Steps to reproduce ( 再現のための前提条件 )

1. step1 system works
2. touch
3. freeze

// If possible, attach a picture of your setup/wiring here.

### Code to reproduce this issue ( 再現させるためのコード )

**Please submit complete source code that can reproduce your problem.**

**void my_touchpad_read(lv_indev_drv_t *indev_driver, lv_indev_data_t *data){
  uint16_t touchX, touchY;
  boolean touched =[ tft.getTouch(&touchX, &touchY);](https://gist.github.com/Red-Owl/eaaadebf16b5d2f21a39b05b1cce65ae)
  if (!touched){
    data->state = LV_INDEV_STATE_REL;
  }else{
    data->state = LV_INDEV_STATE_PR;
    data->point.x = touchX;
    data->point.y = touchY;
  }**

// If your code is longer than 30 lines, [GIST](https://gist.github.com) is preferred.

**Comment by tobozo** [comment]
hi,

> LovyanGFX version: LovyanGFX@1.1.12

please upgrade to 1.1.16, then try with this code:

```cpp

void setup()
{
  tft.init();
}

void loop()
{
  static int count = 0;
  int32_t x, y;
  if (tft.getTouch(&x, &y)) {
    count++;
    tft.fillRect(x-2, y-2, 5, 5, count*7);
  }
}
```
