### ISSUE TITLE
Shimering effect with SSD1963

### ISSUE THREAD

**Issue by tylercamp** [lovyan03/LovyanGFX#583]
I'm using this display with an ESP32 adapter board (available on the same page) which has an SSD1963Q9: https://www.aliexpress.us/item/3256805880921100.html

[Working sample code.zip](https://github.com/user-attachments/files/15986590/src.zip) - In `LCDWIKI_KBV.cpp` see `Set_1963_PWM` at line 726.

(Removed old irrelevant comments)

The original issue here was largely missing backlight control and confusion from an "RS" pin mislabeled as "CD", but with the goal of this GH issue being a well-functioning display, there's still [a shimmering effect](https://github.com/lovyan03/LovyanGFX/issues/583#issuecomment-2192509339) that happens when using LGFX but not when using the attached sample code.

(One of the original issues with backlight control was weird since LGFX init for SSD1963 _does_ include commands to set backlight, not sure why it didn't seem to be working. Maybe a larger compatibility issue with command set?)

~My `LGFX_Device` definition:~

New LGFX config [here](https://github.com/lovyan03/LovyanGFX/issues/583#issuecomment-2191676568)

**Comment by tobozo** [comment]
hi,

    cfg.freq_write = 200000;

200 KHz seems rather slow for a parallel display, have you tried in the MHz range ?

**Comment by tylercamp** [comment]
I set it to 20MHz to start with, and since I wasn't getting any output, I tried lowering it as one of the troubleshooting steps

The adapter board does not expose a backlight pin to the ESP32, and I didn't see a suitable alternative impl. for controlling backlight with SSD1963, so I left that commented out

The sample code I attached shows a command sent to SSD1963 for controlling backlight

**Comment by tobozo** [comment]
sorry I didn't read your full post before replying :blush: 

you can probably take the `Set_1963_PWM()` function from the vendor and implement it inside your LGFX custom class, this is untested code, and the function should be called after `display.init()`: 

```cpp
class LGFX : public lgfx::LGFX_Device
{
  // ... ( your existing config )

    void Set_1963_PWM(uint8_t value)
    {
      uint8_t pwm=value*2.55;
      _bus_instance.writeCommand(0xBE, 8);
      _bus_instance.wait();
      _bus_instance.writeData( 0xBE, 8 );
      _bus_instance.writeData( 0x05, 8 );
      _bus_instance.writeData( pwm, 8 );
      _bus_instance.writeData( 0x01, 8 );
      _bus_instance.writeData( 0xFF, 8 )
      _bus_instance.writeData( 0x00, 8 )
      _bus_instance.writeData( 0x00, 8 );
      _bus_instance.wait();
    }
}
```

if this solves the issue for you then we'll think about a way to include this in the driver without affecting the other SSD1963 variants

**Comment by tobozo** [comment]
maybe `_bus_instance.config().cfg.pin_ctrl[3]` can be used for pulling CD high ? e.g. `cfg.pin_ctrl = { DISPLAY_SSD1963_CD, -1, -1 };` ?

> (The pin is just used to digitalWrite(HIGH) in the LCDWIKI_KBV ctor, but it's also referenced with CD_COMMAND/CD_DATA macros from mcu_8bit_magic.h)

apparently `CD_COMMAND` uses that DC pin too in `LCDWIKI_KBV::reset()`, but I don't know `Panel_SSD1963` well enough to take a guess at how LGFX should handle it, maybe this needs a custom implementation of `Bus_Parallel8` too

**Comment by tylercamp** [comment]
Oh whoops, looks like "CD" was a typo that made its way throughout the sample codebase:

```
#define CD_PIN   15  // Data Command control pin - must use a pin in the range 0-31
```

D/C i.e. RS pin is 15, which is mapped correctly

So it looks like all of the pins are assigned as expected, I'm just not sure why I'm getting shimmering

I tried comparing the init command bytes which are similar but different enough that I can't make a good comparison. I did notice differences in timing values, and changing `xtal_clock` affects the shimmering, so it's likely a timing issue

**Comment by dekesone** [comment]
> sorry I didn't read your full post before replying 😊
> 
> you can probably take the `Set_1963_PWM()` function from the vendor and implement it inside your LGFX custom class, this is untested code, and the function should be called after `display.init()`:
> 
> ```c++
> class LGFX : public lgfx::LGFX_Device
> {
>   // ... ( your existing config )
> 
>     void Set_1963_PWM(uint8_t value)
>     {
>       uint8_t pwm=value*2.55;
>       _bus_instance.writeCommand(0xBE, 8);
>       _bus_instance.wait();
>       _bus_instance.writeData( 0xBE, 8 );
>       _bus_instance.writeData( 0x05, 8 );
>       _bus_instance.writeData( pwm, 8 );
>       _bus_instance.writeData( 0x01, 8 );
>       _bus_instance.writeData( 0xFF, 8 )
>       _bus_instance.writeData( 0x00, 8 )
>       _bus_instance.writeData( 0x00, 8 );
>       _bus_instance.wait();
>     }
> }
> ```
> 
> if this solves the issue for you then we'll think about a way to include this in the driver without affecting the other SSD1963 variants

I have LGFX working great on the same 5" display noted by @tylercamp but have spent the last 6 hours pulling my hair out trying to get the backlight to work properly.  I have the same sample code  (In LCDWIKI_KBV.cpp see Set_1963_PWM at line 726) that properly adjust the backlight PWM, but for the life of me can not get it to work within LGFX,

The example function above provided by @tobozo seems to be close but does not work.  I noticed a few things that I attempted to correct:
      This line is seems to be unnecessary:      _bus_instance.writeData( 0xBE, 8 );
      The writeCommand() should 16 bit length
      There's a few missing ;

But nonetheless still no luck.
I have subsequently dug deeper into the Dynamic Backlight Control and the SSD1963 datasheet.  It seems that after setting the PWM value, you also have to turn on DBC.  Here's the pseudo code from the datasheet:

The hardware pin, PWM is the output signal from SSD1963 to the system backlight driver.  So it should configure PWM module before enable DBC. 
WRITE COMMAND “0xBE” 
WRITE DATA “0x0E” (set PWM frequency) 
WRITE DATA “0xFF” (dummy value if DBC is used) 
WRITE DATA “0x09” (enable PWM controlled by DBC) 
WRITE DATA “0xFF” 
WRITE DATA “0x00” 
WRITE DATA “0x00” 
WRITE COMMAND “0xD4” (Define the threshold value)
 WRITE DATA ..... 
WRITE COMMAND “0xD0” 
WRITE DATA “0x0D”     (Enable DBC with Aggressive mode

Any suggestions on how to proceed?

**Comment by tylercamp** [comment]
@dekesone Could you provide your LGFX config?

**Comment by dekesone** [comment]
Here's what works well for me, minus the PWM backlight obviously.

[gfx_conf.h.txt](https://github.com/user-attachments/files/16085853/gfx_conf.h.txt)

**Comment by tylercamp** [comment]
@dekesone thanks for the reference, I found that I was missing this:

```cpp
      cfg.panel_width = cfg.memory_width = 800;
      cfg.panel_height = cfg.memory_height = 480;
```

I thought I saw init of panel dimensions in the SSD1963 ctor so it seemed unnecessary, but this was the cause of the shimmering I saw.

For the PWM backlight:

> I have subsequently dug deeper into the Dynamic Backlight Control and the SSD1963 datasheet. It seems that after setting the PWM value, you also have to turn on DBC. Here's the pseudo code from the datasheet: ...

The last two lines for enabling DBC are present in the SSD1963 `fixed_cmds`:

```cpp
...
      0xD0, 1, 0x0D, // <-- here (L133)
...
```

... so whatever the underlying backlight issue is, it doesn't seem like it's due to missing DBC init.

**Comment by tylercamp** [comment]
@dekesone Got it! The general commands were correct but there were underlying operations that were missing (e.g. toggling CS pin) since we were interacting with `_bus_instance` directly. I updated the commands to use the same functions as `Panel_SSD1963::init`:

```cpp
  void Set_1963_PWM(uint8_t value)
  {
    startWrite();
    writeCommand16(0xBE);
    _bus_instance.flush();

    writeData( 0x05 );
    writeData( value );
    writeData( 0x01 );
    writeData( 0xFF );
    writeData( 0x00 );
    writeData( 0x00 );

    endWrite();
  }
```

**Comment by tylercamp** [comment]
To summarize:

The shimmering effect I saw was due to incomplete display init. Assigning `panel_width/height` and `memory_width/height` fixed this problem.

We've figured out how to manage backlight control with LGFX and some customizations, but there should be an update to LGFX to properly support this case. #586

**Comment by dekesone** [comment]
Thanks @tylercamp, great work !

**Comment by tobozo** [comment]
@tylercamp thanks for breaking out the different suggested solutions :+1: , I have forwarded the new issue link to lovyan03 as I honestly don't know which one is better since this is beyond my skills

however he's been very busy lately so don't expect a lightning fast answer :wink:

**Comment by tylercamp** [comment]
@dekesone An [update was pushed](https://github.com/lovyan03/LovyanGFX/issues/586#issuecomment-2249590911) to `develop` branch by @lovyan03, are you able to test the update? I'm away from home and don't have a device to test with right now

**Comment by tylercamp** [comment]
@dekesone proper fix merged to 'develop' branch, call 'myLgfx->setBrightness' instead of 'myLgfx->light()->setBrightness' (which is apparently the preferred method in general but the examples get the light directly instead)
