### ISSUE TITLE
"fillGradientRect" not reacting on y-koordinate using "VLINEAR"

### ISSUE THREAD

**Issue by brutzler** [lovyan03/LovyanGFX#601]
**Carefully written Issues are more likely to be given priority.**
**丁寧に記述された報告は優先して対応される可能性が高くなります。**

## Environment ( 実行環境 )

- MCU or Board name:  [ESP-WROOM-32|]
- Panel Driver IC:    [RGB-Display]
- Bus type:          
- LovyanGFX version:  [v1.1.16]
- FrameWork version:   [ArduinoESP32]
- Build Environment:   [PlatformIO]
- Operating System:   [Windows]

## Problem Description ( 問題の内容 )
using fillGradientRect the Y-coordinate looks always to be 0. 

Thats my code.
 tft.fillGradientRect( 300, 199, 150, 300, heatMapGradient, lgfx::VLINEAR );

instead of the "199" it is a "0" used. -> The grafic is always on top of the display.
Using lgfx::RADIAL instead of lgfx::VLINEAR the grafic is moving as expected

### Steps to reproduce ( 再現のための前提条件 )

1. step1
2. ...

// If possible, attach a picture of your setup/wiring here.

### Code to reproduce this issue ( 再現させるためのコード )

**Please submit complete source code that can reproduce your problem.**
**あなたの問題を再現できる完全なソースコードを提示してください。**

```cpp
// the code should be wrapped in the ```cpp tag so that it will be displayed better.
#include "esp_log.h"

void app_main()
{

}

```
// If your code is longer than 30 lines, [GIST](https://gist.github.com) is preferred.

**Comment by brutzler** [comment]
I want to say: whatever y-coordinate I am using (199 in my example), the grafic is not on the expected place. It always stays on the top of the display. Looks like the function is ignoring the value and always using a "0".

**Comment by tobozo** [comment]
hi, thanks for spotting that :+1: 

a [fix](https://github.com/lovyan03/LovyanGFX/commit/043f1147858a51703a383007a96b24ed0aabe771) has been pushed

**Comment by brutzler** [comment]
TY for quick fixing this.
Working now as expected 👍
