### ISSUE TITLE
add request for auto-detect esp32s3-devkitc-1-n8r2

### ISSUE THREAD

**Issue by jonhp** [lovyan03/LovyanGFX#620]
**Carefully written requests are more likely to be given priority.**
**丁寧に記述された要望は優先して対応される可能性が高くなります。**

### Device Name (デバイスの名称・型番等)
esp32s3-devkitc-1-n8r2
spi channels 0 and 1 are spoken for.
so this request is for support for 2 and 3.
also need a way to specify pin numbers to be used to wire the display (ili9341 - https://hiletgo.com/ProductDetail/2157050.html) even with auto detect (multiple #define); although the nicer way would be to support a json confguration file that would separate these kinds of choices from the code itself -- kind of like platformio.ini.

### URL of Device Specifications document (仕様書等のURL)
https://docs.espressif.com/projects/esp-idf/en/latest/esp32s3/hw-reference/esp32s3/user-guide-devkitc-1.html

### URL of the store where we can purchase (商品を購入できるURL)
https://www.digikey.com/en/products/detail/espressif-systems/ESP32-S3-DEVKITC-1-N8R2/15199627

**Comment by tobozo** [comment]
esp32-s3 is already supported and natively detected by this library

Autodetect is for known device bundles e.g. M5Stack, M5CoreS3, ESP32-S3-Box, if your build is custom then you should use a custom LGFX config block

see [lgfx_user](https://github.com/lovyan03/LovyanGFX/tree/master/src/lgfx_user) folder with a few config examples

also see the [discussions tab](https://github.com/lovyan03/LovyanGFX/discussions/categories/device-configurations)

closing this as esp32-s3 ans ili9341 are already supported, so not a device support request
