### ISSUE TITLE
BUG: fillGradientRect() does not respect Y coordinate for vertical gradients

### ISSUE THREAD

**Issue by aldoir** [lovyan03/LovyanGFX#638]
https://github.com/lovyan03/LovyanGFX/blob/50a1800eb771ff8c028334d055ad37e1f12ec863/src/lgfx/v1/LGFXBase.cpp#L1128

Hello, the above line should be updated to 

`        drawFastHLine( x, y+ys, w );
`
in order to properly respect the Y coordinate parameter, otherwise it always use "0" as reference. Could someone please make a PR for this?

**Comment by tobozo** [comment]
hi,

thanks for your feedback :+1: 

[this is already fixed in the develop branch](https://github.com/lovyan03/LovyanGFX/blob/develop/src/lgfx/v1/LGFXBase.cpp#L1128) and will be shipped with the upcoming release
