### ISSUE TITLE
How to use two-point touch on core2 by ft6206U?

### ISSUE THREAD

**Issue by WangYifa** [lovyan03/LovyanGFX#64]

**Comment by lovyan03** [comment]
int x0, y0;
lcd.getTouch( &x0, &y0, 0 );
int x1, y1;
lcd.getTouch( &x1, &y1, 1 );

**Comment by WangYifa** [comment]
on core2 some areas can be touched by two points,and some areas can't

**Comment by WangYifa** [comment]
It's easy to touch two fingers at the opposite corner of the screen
If two fingers touch the screen horizontally at the same time, two points cannot be recognized

**Comment by lovyan03** [comment]
That's the specification of the touch screen. 
It's not a bug.
