### ISSUE TITLE
the code to broadcast the image from the esp32-cam camera to the gc9a01

### ISSUE THREAD

**Issue by marlen-subaru** [lovyan03/LovyanGFX#658]
**Carefully written requests are more likely to be given priority.**
**丁寧に記述された要望は優先して対応される可能性が高くなります。**

### URL of the store where we can purchase (商品を購入できるURL)

Good afternoon, dear authors. Please help me. I have a project based on esp 32-cam and gc9a01 with the TFT_ips library, where the image is broadcast from the camera to the tft screen. But, the frame rate, the speed, is less than what you have here. I recently found your job. And I wanted to use your LovyanGFX library. But I couldn't, I have a lot of mistakes, solving which new ones appear. Help me write the code to broadcast the image from the esp32-cam camera to the gc9a01 tft screen. I am also interested in the possibilities of using resize in this code.
If anything, my email address is: torosyan.marlen@yandex.ru

**Comment by tobozo** [comment]
closing this as redundant with #659
