### ISSUE TITLE
error: no matching function for call to 'max(int, long int)'

### ISSUE THREAD

**Issue by matsujirushi** [lovyan03/LovyanGFX#73]
I got below error for Wio Terminal.

```
.pio\libdeps\seeed_wio_terminal\LovyanGFX\src\lgfx\panel\Panel_IT8951.cpp:411:82: error: no matching function for call to 'max(int, long int)'
                 pixel = std::min(15, std::max(0, pixel + btbl[(x + prev_pos) & 3]) >> 6);
                                                                                  ^
```

![image](https://user-images.githubusercontent.com/8079404/101461325-0b1c5200-397e-11eb-87c1-bb41176c1641.png)

**Comment by lovyan03** [comment]
Thanks for reporting this !
I've hastily reflected the fixes in the develop branch.

**Comment by matsujirushi** [comment]
Super!

I checked. It is fine.
![image](https://user-images.githubusercontent.com/8079404/101465768-b2e84e80-3983-11eb-9766-b86536c28eab.png)

Thank you.

**Comment by Kabron287** [comment]
I applyed the fix, but got:
Panel_IT8951.cpp: 411:82: error: no matching function for call to 'max(int, long int)
                 pixel = std*: min(15, std::max(0, pixel + btbl[(x + prev_pos) & 3]) >> 6)

**Comment by Kabron287** [comment]
pixel = std::min(15, std::max(0, (int)(pixel + btbl[(x + prev_pos) & 3] >> 6)));
Solved it.

**Comment by lovyan03** [comment]
The fix has been made to the develop branch and is not yet reflected in the master branch.
