### ISSUE TITLE
ESPIDF環境でLGFX_M5STICK_Cを定義してもAutodetect failになる

### ISSUE THREAD

**Issue by ixsiid** [lovyan03/LovyanGFX#79]
参考までにLGFX_Config_AutoDetectESP32.hpp:558の行末コメントを解除することで認識しました

**Comment by lovyan03** [comment]
ご報告ありがとうございます！
動作テスト中に行ったコメントアウトをうっかりそのままコミットしていたようです…お恥ずかしい…。

**Comment by lovyan03** [comment]
本件修正を含む バージョン0.3.4リリースしました。ありがとうございました！
