### ISSUE TITLE
How to display image with ESP32 3.5" TFT touch(capacitive) board

### ISSUE THREAD

**Issue by gigwegbe** [lovyan03/LovyanGFX#84]
Hello @lovyan03,
I have ESP32 3.5" TFT touch(capacitive) board and I want to push the image from the camera with CAMERA_PIXEL_FORMAT -> PIXFORMAT_GRAYSCALE however, I got the result below. 
![image](https://user-images.githubusercontent.com/25044700/102724326-13c24000-430f-11eb-9131-392e06a7a6f2.png)

``` camera_fb_t *img = capture();
    if (img == nullptr || img == 0) 
    {
        Serial.printf("snap fail\n");
        return;
    }

    tft.pushImage(0, 0, 96, 96, (lgfx::swap565_t*)img->buf); 
}
```
How do I display a grayscale image on the TFT screen?
For more details check the repo - [Link](https://github.com/gigwegbe/person-detection-with-esp32)

**Comment by lovyan03** [comment]
@gigwegbe 
I have now added a new type "lgfx::grayscale_t" to the develop branch.
Try to get the latest develop branch and cast it to lgfx::grayscale_t instead of lgfx::swap565_t .

**Comment by gigwegbe** [comment]
Thanks @lovyan03, 
Worked like a charm.
![image](https://user-images.githubusercontent.com/25044700/102759386-5407d980-4374-11eb-86fb-821b57dabf1c.png)
